%% DEMO_JPL_ASTEROID_SKY
% Example calls for plot_JPL_asteroid_sky.m
%
% Required files on the MATLAB path:
%   plot_JPL_asteroid_sky.m
%   milkyway.m

%% 1) Recommended Earth-centered RA/Dec map, degrees, irregular Milky Way
plot_JPL_asteroid_sky( ...
    "geocentric", ...
    datetime('now','TimeZone','UTC'), ...
    Population="MBA", ...
    CoordinateFrame="equatorial", ...
    RAUnits="degrees", ...
    LongitudeDirection="increasing_right", ...
    MilkyWaySource="legacy_footprint", ...
    ShowGalacticEquator=true, ...
    Verbose=false);

%% 2) Same snapshot in J2000 ecliptic longitude/latitude
plot_JPL_asteroid_sky( ...
    "geocentric", ...
    datetime('now','TimeZone','UTC'), ...
    Population="MBA", ...
    CoordinateFrame="ecliptic", ...
    LongitudeDirection="increasing_right", ...
    MilkyWaySource="legacy_footprint", ...
    ShowGalacticEquator=true, ...
    Verbose=false);

%% 3) Galactic-frame validation
% The dashed Galactic equator must be exactly horizontal at b=0 deg.
% The irregular historical footprint should straddle it, not become a
% constant-width horizontal band.
plot_JPL_asteroid_sky( ...
    "geocentric", ...
    datetime('now','TimeZone','UTC'), ...
    Population="MBA", ...
    CoordinateFrame="galactic", ...
    LongitudeDirection="increasing_right", ...
    MilkyWaySource="legacy_footprint", ...
    ShowGalacticEquator=true, ...
    Verbose=false);

%% 4) All characterized asteroids, heliocentric ecliptic view with planets
plot_JPL_asteroid_sky( ...
    "heliocentric", ...
    datetime('now','TimeZone','UTC'), ...
    Population="all_asteroids", ...
    CoordinateFrame="ecliptic", ...
    LongitudeDirection="increasing_right", ...
    MilkyWaySource="legacy_footprint", ...
    ShowPlanets=true, ...
    ShowPlanetLabels=true, ...
    Verbose=false);

%% 5) Idealized Galactic-latitude band instead of the historical footprint
plot_JPL_asteroid_sky( ...
    "geocentric", ...
    datetime('now','TimeZone','UTC'), ...
    Population="MBA", ...
    CoordinateFrame="equatorial", ...
    RAUnits="degrees", ...
    MilkyWaySource="galactic_band", ...
    MilkyWayHalfWidth_deg=12, ...
    ShowGalacticEquator=true, ...
    Verbose=false);

%% ========================================================================
%  FILTER EXAMPLES
% =========================================================================

% Large main-belt asteroids only (D >= 100 km)
% plot_JPL_asteroid_sky( ...
%     "geocentric", ...
%     datetime('now','TimeZone','UTC'), ...
%     Population="MBA", ...
%     DiameterRange_km=[100 Inf], ...
%     Verbose=false);

% Fast rotators only (>= 5 rev/day)
% plot_JPL_asteroid_sky( ...
%     "geocentric", ...
%     datetime('now','TimeZone','UTC'), ...
%     Population="all_asteroids", ...
%     SpinRateRange_revDay=[5 Inf], ...
%     Verbose=false);

% Combined filter: 20--200 km and 0.5--4 rev/day
% plot_JPL_asteroid_sky( ...
%     "heliocentric", ...
%     datetime('now','TimeZone','UTC'), ...
%     Population="all_asteroids", ...
%     DiameterRange_km=[20 200], ...
%     SpinRateRange_revDay=[0.5 4], ...
%     Verbose=false);
