%% DEMO_CR3BP_FLOQUET_MULTI_PARENT_OVERLAY
% Multi-parent ideal-CR3BP Floquet-normal sky overlays.
%
% The expensive geometry is built ONCE per system and then reused by both
% the asteroid-sky figure and the linked 3-D orbit / celestial-sphere figure.
% This avoids duplicate Horizons queries and duplicate Floquet calculations.

clear;
clc;

% Text uses LaTeX. Plot figures themselves use a white background by default.
set(groot,'DefaultTextInterpreter','latex');
set(groot,'DefaultAxesTickLabelInterpreter','latex');
set(groot,'DefaultLegendInterpreter','latex');

epochUTC = datetime('now','TimeZone','UTC');

%% ========================================================================
% EARTH-MOON
% =========================================================================
systemName = "EarthMoon";
poFile = "L1_northern_halo_orbits_JPL_IC_Earth_Moon.csv";
parentRows = [82 125 197];

overlaysEM = make_cr3bp_floquet_normal_overlays( ...
    systemName,poFile,parentRows,epochUTC, ...
    CenterMode="vertical", ...
    NPrimaryPeriods=1, ...
    SamplesPerPeriod=600, ...
    MassRatioSource="catalog", ...
    ShowAntipode=true, ...
    ColorMode="gradient", ...
    ColorMapName="turbo", ...
    ColorParameter="sequence", ...
    Verbose=true);

plot_JPL_asteroid_sky( ...
    "geocentric",epochUTC, ...
    Population="MBA", ...
    CoordinateFrame="ecliptic", ...
    LongitudeDirection="increasing_right", ...
    NormalOverlay=overlaysEM, ...
    Verbose=false);

plot_cr3bp_floquet_orbits_and_sky( ...
    systemName,poFile,parentRows,epochUTC, ...
    Overlays=overlaysEM, ...
    SkyFrame="ecliptic", ...
    Verbose=false);

%% ========================================================================
% SUN-EARTH
% =========================================================================
systemNameSE = "SunEarth";
poFileSE = "Butterfly_orbits_JPL_IC_Sun_Earth.csv";
parentRowsSE = [1:10];

overlaysSE = make_cr3bp_floquet_normal_overlays( ...
    systemNameSE,poFileSE,parentRowsSE,epochUTC, ...
    CenterMode="vertical", ...
    NPrimaryPeriods=2, ...
    SamplesPerPeriod=600, ...
    MassRatioSource="catalog", ...
    ShowAntipode=true, ...
    ColorMode="gradient", ...
    ColorMapName="parula", ...
    ColorParameter="parentRow", ...
    Verbose=true);

% In Sun-Earth, the primary body (Sun) is hidden by default because its
% rendered size can dominate the local L1/L2 orbit view. To show it, add
% ShowPrimaryBody=true to the call below.
plot_cr3bp_floquet_orbits_and_sky( ...
    systemNameSE,poFileSE,parentRowsSE,epochUTC, ...
    Overlays=overlaysSE, ...
    SkyFrame="ecliptic", ...
    Verbose=false);

% Optional: place the Sun-Earth normal tracks on the heliocentric asteroid sky.
  plot_JPL_asteroid_sky( ...
    "heliocentric",epochUTC, ...
    Population="all_asteroids", ...
    CoordinateFrame="ecliptic", ...
    NormalOverlay=overlaysSE, ...
    Verbose=false);



  %% 

  handles = launch_cr3bp_family_visualizer( ...
  systemNameSE,poFileSE,overlaysSE,epochUTC, ...
      Observer="heliocentric", ...
      Population="all_asteroids", ...
      CoordinateFrame="ecliptic", ...
      ShowMilkyWay=true, ...
      ShowPlanets=false, ...
      ShowPrimaryBody=false, ...
      ShowSecondaryBody=true, ...
      AutoRefresh=true);

