function overlay = make_halo_floquet_normal_overlay(epochUTC,opts)
%MAKE_HALO_FLOQUET_NORMAL_OVERLAY Backward-compatible single-parent wrapper.
%
% This wrapper preserves the earlier API while routing all calculations
% through the generic multi-parent/multi-system implementation
% make_cr3bp_floquet_normal_overlays.
%
% New work should normally call make_cr3bp_floquet_normal_overlays directly.

arguments
    epochUTC (1,1) datetime = datetime('now','TimeZone','UTC')

    opts.SystemName (1,1) string = "EarthMoon"
    opts.POFile (1,1) string = ...
        "L1_northern_halo_orbits_JPL_IC_Earth_Moon.csv"
    opts.ParentRow (1,1) double {mustBeInteger,mustBePositive} = 116
    opts.CenterMode (1,1) string = "vertical"
    opts.NPrimaryPeriods (1,1) double {mustBeInteger,mustBePositive} = 1
    opts.SamplesPerPeriod (1,1) double {mustBeInteger,mustBePositive} = 600
    opts.FloquetPhaseSamples (1,1) double {mustBeInteger,mustBePositive} = 61
    opts.OrbitSamples (1,1) double {mustBeInteger,mustBePositive} = 800
    opts.NormalReferenceSynodic (1,3) double = [1 0 0]
    opts.EmbeddingMode (1,1) string = "ideal_epoch_anchor"
    opts.PrimaryHorizonsID (1,1) string = ""
    opts.SecondaryHorizonsID (1,1) string = ""
    opts.InitialSynodicToEcliptic double = []
    opts.MassRatioSource (1,1) string = "catalog"
    opts.MassRatio (1,1) double = NaN
    opts.CheckOrbitClosure (1,1) logical = true
    opts.OrbitClosureTolerance (1,1) double {mustBePositive} = 1e-8
    opts.ShowAntipode (1,1) logical = true
    opts.Verbose (1,1) logical = true
    opts.LineWidth (1,1) double {mustBePositive} = 2.4
    opts.Color (1,3) double = [0.88 0.08 0.08]
    opts.Label (1,1) string = ""
end

allOverlays = make_cr3bp_floquet_normal_overlays( ...
    opts.SystemName, ...
    opts.POFile, ...
    opts.ParentRow, ...
    epochUTC, ...
    CenterMode=opts.CenterMode, ...
    NPrimaryPeriods=opts.NPrimaryPeriods, ...
    SamplesPerPeriod=opts.SamplesPerPeriod, ...
    FloquetPhaseSamples=opts.FloquetPhaseSamples, ...
    OrbitSamples=opts.OrbitSamples, ...
    NormalReferenceSynodic=opts.NormalReferenceSynodic, ...
    EmbeddingMode=opts.EmbeddingMode, ...
    PrimaryHorizonsID=opts.PrimaryHorizonsID, ...
    SecondaryHorizonsID=opts.SecondaryHorizonsID, ...
    InitialSynodicToEcliptic=opts.InitialSynodicToEcliptic, ...
    MassRatioSource=opts.MassRatioSource, ...
    MassRatio=opts.MassRatio, ...
    CheckOrbitClosure=opts.CheckOrbitClosure, ...
    OrbitClosureTolerance=opts.OrbitClosureTolerance, ...
    ShowAntipode=opts.ShowAntipode, ...
    LineWidth=opts.LineWidth, ...
    Colors=opts.Color, ...
    Labels=opts.Label, ...
    Verbose=opts.Verbose);

overlay = allOverlays(1);

end
