function figsObs = plot_simulated_interferometric_observations( ...
    obs, phaseAmpThreshold)
%PLOT_SIMULATED_INTERFEROMETRIC_OBSERVATIONS
%
% Plot visibility amplitude and phase for an arbitrary number of baselines.
%
% The phase panel only shows samples with
%
%       |V| > phaseAmpThreshold
%
% because visibility phase is not meaningful when the complex visibility
% is close to zero.
%
% INPUTS
%   obs :
%       Output from make_simulated_interferometric_observations.
%
%   phaseAmpThreshold :
%       Minimum visibility amplitude for displaying phase.
%
% OUTPUT
%   figsObs :
%       Structure containing the generated figure handles.


%% Validate inputs

if ~isstruct(obs)
    error('obs must be a structure.');
end

requiredFields = { ...
    'targetType', ...
    'nBaselines', ...
    'baselines'};

for k = 1:numel(requiredFields)

    if ~isfield(obs, requiredFields{k})
        error('obs.%s is required.', requiredFields{k});
    end

end

if nargin < 2 || isempty(phaseAmpThreshold)
    phaseAmpThreshold = 1e-5;
end

if ~isscalar(phaseAmpThreshold) || ...
   ~isfinite(phaseAmpThreshold) || ...
   phaseAmpThreshold < 0

    error('phaseAmpThreshold must be a nonnegative finite scalar.');

end


%% Initialize

figsObs = struct();

baselineColors = lines(obs.nBaselines);


%% Create figure

figsObs.visibility = figure( ...
    'Name', 'Simulated visibility observations', ...
    'Color', 'w', ...
    'Position', [100 100 1200 520]);

tl = tiledlayout( ...
    figsObs.visibility, ...
    1, ...
    2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');


%% Visibility-amplitude panel

ax1 = nexttile(tl);

hold(ax1, 'on');
grid(ax1, 'on');
box(ax1, 'on');


%% Visibility-phase panel

ax2 = nexttile(tl);

hold(ax2, 'on');
grid(ax2, 'on');
box(ax2, 'on');


%% Plot each baseline

for k = 1:obs.nBaselines

    b = obs.baselines(k);

    requiredBaselineFields = { ...
        'rho_Glambda', ...
        'amplitude', ...
        'phase_deg', ...
        'name'};

    for j = 1:numel(requiredBaselineFields)

        if ~isfield(b, requiredBaselineFields{j})

            error( ...
                'obs.baselines(%d).%s is required.', ...
                k, ...
                requiredBaselineFields{j});

        end

    end

    rho = b.rho_Glambda(:);
    amplitude = b.amplitude(:);
    phaseDeg = b.phase_deg(:);

    if numel(rho) ~= numel(amplitude) || ...
       numel(rho) ~= numel(phaseDeg)

        error( ...
            'Baseline %d has inconsistent observation-array lengths.', ...
            k);

    end


    %% Visibility amplitude

    scatter( ...
        ax1, ...
        rho, ...
        amplitude, ...
        22, ...
        baselineColors(k,:), ...
        'filled', ...
        'DisplayName', ...
        b.name);


    %% Visibility phase

    idxGood = ...
        amplitude > phaseAmpThreshold & ...
        isfinite(phaseDeg);

    scatter( ...
        ax2, ...
        rho(idxGood), ...
        phaseDeg(idxGood), ...
        22, ...
        baselineColors(k,:), ...
        'filled', ...
        'DisplayName', ...
        b.name);

end


%% Format amplitude panel

xlabel( ...
    ax1, ...
    '$\rho_{uv}$ [$\mathrm{G}\lambda$]', ...
    'Interpreter', 'latex');

ylabel( ...
    ax1, ...
    '$|V|$', ...
    'Interpreter', 'latex');

title( ...
    ax1, ...
    'Visibility amplitude', ...
    'Interpreter', 'latex');

legend( ...
    ax1, ...
    'Location', 'best');


%% Format phase panel

xlabel( ...
    ax2, ...
    '$\rho_{uv}$ [$\mathrm{G}\lambda$]', ...
    'Interpreter', 'latex');

ylabel( ...
    ax2, ...
    '$\arg(V)$ [deg]', ...
    'Interpreter', 'latex');

title( ...
    ax2, ...
    sprintf( ...
        'Visibility phase, $|V| > %.0e$', ...
        phaseAmpThreshold), ...
    'Interpreter', 'latex');

legend( ...
    ax2, ...
    'Location', 'best');


%% Match axes

xlim(ax2, xlim(ax1));

ylim(ax2, [-180 180]);


%% Overall title

targetTypeDisplay = strrep( ...
    obs.targetType, ...
    '_', ...
    ' ');

title( ...
    tl, ...
    sprintf( ...
        'Simulated observations: %s', ...
        targetTypeDisplay), ...
    'Interpreter', 'none');

end