%% RUN_QPO_Floquet_Normal_Breakdown_Study
%
% FINESST / GMOS
%
% FINITE-QPO BREAKDOWN OF THE LINEAR FLOQUET FORMATION PREDICTOR
%
% Goal
% ----
% Quantify how the exact finite-amplitude three-collector QPO formation
% departs from the parent periodic orbit's linear transported Floquet plane
% as the corrected torus size grows.
%
% This study tests four distinct predictions of the linear model:
%
%   1. Normal-track prediction
%
%          n_QPO(t) -> n_F(t)
%
%      as torus size -> 0.
%
%   2. Phase independence
%
%      In the linear model, all collector phase choices lie in the same
%      transported Floquet plane.  Therefore finite phase spread should
%      vanish as size -> 0.
%
%   3. Parent-period plane closure
%
%          n_F(t+T) = +/- n_F(t)
%
%      exactly in the linear model.  Finite-QPO non-closure measures how
%      strongly higher harmonics make the triangle plane genuinely
%      quasiperiodic.
%
%   4. Linear baseline breathing
%
%      After calibrating the arbitrary Floquet eigenvector scale to the
%      actual corrected QPO section RMS radius, compare finite B_RMS(t)
%      against the linear prediction.
%
% Family construction
% -------------------
% Each parent uses TWO nearby small corrected seeds followed by the existing
% fixed-T pseudo-arclength continuation routine:
%
%       gmos_continue_fixT_family
%
% We deliberately do NOT solve a list of unrelated seed amplitudes because
% independent Newton solves can jump to unrelated QPO branches.
%
% Main outputs
% ------------
% For every analyzed family member:
%
%   actual corrected torus RMS radius [km]
%   median and worst Floquet-normal error across starting phases
%   nonlinear phase-spread metric
%   period-to-period plane non-closure
%   baseline-breathing relative error
%   nonlinear rho departure
%
% The default parent set contains ten representative halo parents spanning
% the catalog-row regime where genuine nontrivial center pairs were found.
%
% For each parent, the script also fits a local power law
%
%       delta_n,RMS ~ C R^p
%
% over the smallest members lying below the configured error ceiling.
%
% Recommended interpretation
% --------------------------
% If p ~ 1, the generic O(R) correction is present.
% If p ~ 2, symmetry cancels the first-order angular correction and the
% linear Floquet surrogate is substantially better than the generic estimate.
%
% Required existing functions
% ---------------------------
%   cr3bp_system_parameters
%   choose_periodic_orbit
%   gmos_demo_invariance_only
%   gmos_pack_z
%   gmos_unpack_z
%   gmos_newton_fixT_analytic
%   gmos_continue_fixT_family
%   qpo_equal_phase_indices
%   compute_three_collector_qpo_geometry
%   monodromy_CR3BP
%   gmos_center_eigpair_from_eigs
%   transport_floquet_center_geometry_CR3BP
%
% New helpers supplied with this study
% ------------------------------------
%   build_gmos_fixedT_amplitude_family
%   evaluate_finite_qpo_vs_floquet

clear;
clc;
close all;


%% ============================================================
%  0. PLOT DEFAULTS
%  ============================================================

set(groot,'DefaultTextInterpreter','latex');
set(groot,'DefaultAxesTickLabelInterpreter','latex');
set(groot,'DefaultLegendInterpreter','latex');

set(groot,'DefaultAxesFontSize',14);
set(groot,'DefaultTextFontSize',16);

set(groot,'DefaultFigureColor','w');
set(groot,'DefaultAxesColor','w');
set(groot,'DefaultAxesXColor','k');
set(groot,'DefaultAxesYColor','k');
set(groot,'DefaultTextColor','k');


%% ============================================================
%  1. STUDY CONFIGURATION
%  ============================================================

systemName = 'EarthMoon';

sys = cr3bp_system_parameters(systemName);


poFile = ...
    'L1_northern_halo_orbits_JPL_IC_Earth_Moon.csv';


% Clean progression from modest to much broader Floquet-plane motion.
% Baseline parents from the first study plus three larger-|z0| parents
% that still possess genuine nontrivial unit-circle center candidates in
% the full Floquet survey.
%
%   row 161 : |z0| ~= 0.207 LU, vertical-dominant center candidate
%   row 294 : |z0| ~= 0.288 LU, isolated large-halo center candidate
%   row 296 : |z0| ~= 0.292 LU, isolated large-halo center candidate
%
% NOTE: JPL catalog row is an inventory coordinate, not a continuation
% coordinate.  In particular rows 294--296 belong to an isolated
% center-candidate cluster and should be treated as stress-test cases rather
% than as a smooth continuation of row 197.
% Representative parents spanning the catalog-row regime in which a
% genuine nontrivial center pair exists.  Catalog row is still only an
% inventory coordinate; this is a morphology survey, not a continuation
% diagram of the halo family itself.
%
% Early/main center-candidate run : 20, 60, 82, 125
% End of main run                : 150
% Intermittent later candidates  : 161, 197, 250
% Isolated large-halo candidates : 294, 296
parentRows = [20 60 82 125 150 161 197 250 294 296];


%% GMOS family generation

N = 51;

mode = 'vertical';


% Two small nearby seeds only.  The remaining family comes from continuation.
KSeeds = [1e-5 3e-5];


% Number of PALC steps AFTER the two corrected startup members.
nContinuationSteps = 180;


% PALC step is chosen relative to the corrected startup secant norm:
%
%   ds = multiplier * ||z1-z0||
%
% Start conservatively. Increase only after inspecting family smoothness.
continuationStepMultiplier = 4.0;


newtonOpts = struct();

newtonOpts.maxIter = 20;
newtonOpts.tolInf = 1e-10;
newtonOpts.verbose = false;


odeOpts = odeset( ...
    'RelTol',1e-12, ...
    'AbsTol',1e-12);


%% Formation evaluation

nCollectors = 3;

normalReferenceSynodic = [1 0 0];


% IMPORTANT:
% The finite QPO is propagated for TWO parent periods.
%
%   - the primary Floquet-normal error is evaluated on the FIRST period;
%   - the SECOND period exists only so that one-period plane non-closure can
%     be measured.
%
% The linear Floquet predictor itself is computed over one parent period and
% then treated as periodic as a plane.
nPrimaryPeriods = 2;

nSavePerPrimaryPeriod = 250;


% The full continued family may contain dozens of members.  Analyze a
% radius-distributed subset with all distinct phases.
maxFamilyMembersToAnalyze = 20;

% Always retain the first few corrected family members so the numerical
% floor and the small-amplitude asymptotic regime remain well resolved even
% when the continuation reaches much larger tori.
nSmallMembersToAlwaysAnalyze = 5;


%% Local convergence-law fit

% Floor-aware model used for quantities that visibly approach a finite
% numerical/discretization floor:
%
%   E(R) = sqrt( E_floor^2 + (C R^p)^2 ).
%
% This prevents the floor from biasing p toward zero.
fitMaxErrorDeg = 0.5;

fitMaxPoints = 12;

fitMinPoints = 5;


%% Linear predictor sampling

nFloquetSamples = nSavePerPrimaryPeriod + 1;

nFloquetPhaseSamples = 61;


%% Saving

saveResults = true;

outputDir = fullfile( ...
    pwd, ...
    'QPO_Floquet_Normal_Breakdown_Study');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end


%% Figure export

saveFigures = true;

% PNG is convenient for reports / quick inspection.
saveFigurePNG = true;
figurePNGResolution = 300;

% MATLAB FIG retains full editability.
saveFigureFIG = true;

% Optional vector PDF.  Disabled by default because sphere/surface figures
% can become large.  Turn on if you want publication-vector exports.
saveFigurePDF = false;


%% ============================================================
%  2. GLOBAL STORAGE
%  ============================================================

nParents = numel(parentRows);

parentResults = cell(nParents,1);

parentSucceeded = false(nParents,1);
parentFailureMessage = strings(nParents,1);

allRows = {};


%% ============================================================
%  3. PARENT LOOP
%  ============================================================

for ip = 1:nParents

    orbitIndex = parentRows(ip);


    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('PARENT %d / %d : JPL ROW %d\n', ...
        ip,nParents,orbitIndex);
    fprintf('============================================================\n');


    po = choose_periodic_orbit( ...
        poFile, ...
        orbitIndex, ...
        sys);

    fprintf('Parent z0                 = %.9f LU\n',po.x0(3));
    fprintf('Parent |z0|               = %.9f LU\n',abs(po.x0(3)));
    fprintf('Parent period             = %.9f TU\n',po.T);


    %% --------------------------------------------------------
    %  3.1 Linear Floquet predictor for this parent
    %  --------------------------------------------------------

    M_eigs = monodromy_CR3BP( ...
        [0,po.T], ...
        po.x0(:), ...
        sys.mu);


    V = M_eigs(:,1:6);
    D = M_eigs(:,7:12);


    centerOpts = struct();

    centerOpts.tolUnit = 1e-6;
    centerOpts.tolImag = 1e-10;
    centerOpts.warnMismatch = false;


    cen = gmos_center_eigpair_from_eigs( ...
        V, ...
        D, ...
        mode, ...
        centerOpts);


    floquetGeom = ...
        transport_floquet_center_geometry_CR3BP( ...
            [0,po.T], ...
            po.x0(:), ...
            sys.mu, ...
            cen.w, ...
            nFloquetSamples, ...
            odeOpts, ...
            nFloquetPhaseSamples);


    fprintf('Linear center rho/(2pi) = %.8f cycles\n', ...
        cen.rho0_cycles);

    fprintf('Floquet normal RMS excursion = %.6f deg\n', ...
        floquetGeom.metrics.synodic.RMSExcursion_deg);


    %% --------------------------------------------------------
    %  3.2 Build ONE continuous fixed-T finite-QPO family
    %  --------------------------------------------------------

    try

        family = ...
            build_gmos_fixedT_amplitude_family( ...
                po, ...
                sys, ...
                N, ...
                KSeeds, ...
                mode, ...
                nContinuationSteps, ...
                continuationStepMultiplier, ...
                odeOpts, ...
                newtonOpts);

    catch ME

        warning( ...
            ['Skipping parent row %d because the finite-QPO startup / ', ...
             'continuation family could not be constructed:%s'], ...
            orbitIndex, ...
            ME.message);

        parentFailureMessage(ip) = ...
            string(ME.message);

        failedParent = struct();

        failedParent.orbitIndex = orbitIndex;
        failedParent.po = po;
        failedParent.cen = cen;
        failedParent.floquetGeom = floquetGeom;
        failedParent.failed = true;
        failedParent.failureMessage = string(ME.message);

        parentResults{ip} = failedParent;

        continue

    end


    nFamily = numel(family.fam.z);


    fprintf('Accepted family members = %d\n',nFamily);
    fprintf('Continuation ds         = %.6e\n',family.ds);

    fprintf('Radius range             = %.6g to %.6g km\n', ...
        min(family.radiusRMS_km), ...
        max(family.radiusRMS_km));

    fprintf('Jacobi analysis limit    = %.3e\n', ...
        family.jacobiLimit);

    fprintf('Resolution-valid members = %d / %d\n', ...
        nnz(family.analysisValid), ...
        numel(family.analysisValid));


    %% --------------------------------------------------------
    %  3.3 Choose family members distributed across ACTUAL radius
    %  --------------------------------------------------------

    radiusForSelection = ...
        family.radiusRMS_km;

    radiusForSelection(~family.analysisValid) = ...
        NaN;


    familyIdx = ...
        choose_radius_distributed_members( ...
            radiusForSelection, ...
            maxFamilyMembersToAnalyze, ...
            nSmallMembersToAlwaysAnalyze);


    fprintf('Analyzing family indices: ');
    fprintf('%d ',familyIdx);
    fprintf('\n');


    %% Physically distinct common starting phases

    phaseStartIndices = ...
        unique_equal_phase_start_indices( ...
            N, ...
            nCollectors);


    fprintf('Distinct 3-collector phase cases = %d\n', ...
        numel(phaseStartIndices));


    %% --------------------------------------------------------
    %  3.4 Evaluate selected finite tori
    %  --------------------------------------------------------

    nCases = numel(familyIdx);

    caseResults = cell(nCases,1);


    for ic = 1:nCases

        iFam = familyIdx(ic);


        [XCurve,TQPO,rhoQPO] = ...
            gmos_unpack_z( ...
                family.fam.z{iFam}, ...
                N);


        fprintf('\n');
        fprintf('  family member %d/%d (family index %d)\n', ...
            ic,nCases,iFam);

        fprintf('    R_rms = %.6f km\n', ...
            family.radiusRMS_km(iFam));

        fprintf('    rho/(2pi) = %.10f\n', ...
            rhoQPO/(2*pi));


        result = ...
            evaluate_finite_qpo_vs_floquet( ...
                XCurve, ...
                TQPO, ...
                rhoQPO, ...
                po, ...
                sys, ...
                floquetGeom, ...
                nCollectors, ...
                phaseStartIndices, ...
                nPrimaryPeriods, ...
                nSavePerPrimaryPeriod, ...
                odeOpts, ...
                normalReferenceSynodic);


        result.familyIndex = iFam;
        result.jacobiSpread = family.jacobiSpread(iFam);

        caseResults{ic} = result;


        allRows(end+1,:) = { ...
            orbitIndex, ...
            iFam, ...
            result.sectionRadiusRMS_km, ...
            rhoQPO/(2*pi), ...
            result.rhoError_rad, ...
            family.jacobiSpread(iFam), ...
            result.summary.normalTrackE50_deg, ...
            result.summary.normalTrackE95_deg, ...
            result.summary.normalTrackEmax_deg, ...
            result.summary.qAMinFirst, ...
            result.phaseSpreadRMS_deg, ...
            result.summary.periodClosureMedianRMS_deg, ...
            result.summary.baselineRelErrorMedianRMS, ...
            result.summary.medianBaseline_km};

    end


    %% --------------------------------------------------------
    %  3.5 Sort analyzed cases by actual physical radius
    %  --------------------------------------------------------

    radius_km = ...
        cellfun( ...
            @(x) x.sectionRadiusRMS_km, ...
            caseResults);


    [radius_km,sortIdx] = ...
        sort(radius_km);


    caseResults = ...
        caseResults(sortIdx);


    familyIdxSorted = ...
        familyIdx(sortIdx);


    %% --------------------------------------------------------
    %  3.6 Power-law fits in the small-error regime
    %  --------------------------------------------------------

    normalMedian = ...
        cellfun( ...
            @(x) x.summary.normalTrackE50_deg, ...
            caseResults);


    phaseSpread = ...
        cellfun( ...
            @(x) x.phaseSpreadRMS_deg, ...
            caseResults);


    periodClosure = ...
        cellfun( ...
            @(x) x.summary.periodClosureMedianRMS_deg, ...
            caseResults);


    baselineError = ...
        cellfun( ...
            @(x) x.summary.baselineRelErrorMedianRMS, ...
            caseResults);


    rhoError = ...
        cellfun( ...
            @(x) x.rhoError_rad, ...
            caseResults);


    % The raw normal error contains a clear parent-dependent floor.  Fit
    %
    %   E(R) = sqrt(E_floor^2 + (C R^p)^2)
    %
    % rather than E = C R^p.
    fitNormal = ...
        fit_floor_power_law( ...
            radius_km, ...
            normalMedian, ...
            fitMaxErrorDeg, ...
            fitMaxPoints, ...
            fitMinPoints);


    % Phase spread and period non-closure are zero in the exact linear
    % model.  Very small finite formations can nevertheless be dominated by
    % numerical differencing / propagation noise.  Fit only the resolved
    % rising branch after the observed minimum.
    fitPhase = ...
        fit_post_floor_power_law( ...
            radius_km, ...
            phaseSpread, ...
            fitMaxErrorDeg, ...
            fitMaxPoints, ...
            fitMinPoints);


    fitClosure = ...
        fit_post_floor_power_law( ...
            radius_km, ...
            periodClosure, ...
            fitMaxErrorDeg, ...
            fitMaxPoints, ...
            fitMinPoints);


    % Baseline-relative error visibly has a finite floor from interpolation /
    % finite discretization, so fit it with the same floor-aware model.
    fitBaseline = ...
        fit_floor_power_law( ...
            radius_km, ...
            baselineError, ...
            Inf, ...
            fitMaxPoints, ...
            fitMinPoints);


    % Rotation-number departure should be quadratic in amplitude, but the
    % very smallest corrected tori can be dominated by numerical scatter.
    % Detect the minimum-error floor automatically and fit only the rising
    % post-floor branch.  This fixes cases such as row 161 without adding a
    % user-tuned threshold.
    fitRho = ...
        fit_post_floor_power_law( ...
            radius_km, ...
            rhoError, ...
            Inf, ...
            fitMaxPoints, ...
            fitMinPoints);


    %% Validity radii for simple angular tolerances
    %
    % If the threshold is never crossed, report the largest tested radius as
    % a LOWER BOUND rather than pretending it is the actual validity limit.

    valid1 = ...
        estimate_error_threshold( ...
            radius_km, ...
            normalMedian, ...
            1.0);


    valid5 = ...
        estimate_error_threshold( ...
            radius_km, ...
            normalMedian, ...
            5.0);


    fprintf('\nParent row %d summary\n',orbitIndex);

    fprintf('  fitted normal-error floor E0 = %.6e deg\n', ...
        fitNormal.floor);

    fprintf('  floor-corrected normal power p = %.6f\n', ...
        fitNormal.p);

    fprintf('  post-floor phase-spread power p= %.6f\n', ...
        fitPhase.p);

    fprintf('  post-floor closure power p     = %.6f\n', ...
        fitClosure.p);

    fprintf('  fitted baseline-error floor    = %.6e\n', ...
        fitBaseline.floor);

    fprintf('  baseline nonlinear power p     = %.6f\n', ...
        fitBaseline.p);

    fprintf('  rotation-number power p        = %.6f\n', ...
        fitRho.p);

    print_threshold_result('1 deg',valid1);
    print_threshold_result('5 deg',valid5);


    %% --------------------------------------------------------
    %  3.7 Parent plots
    %  --------------------------------------------------------

    fig1 = ...
        make_parent_error_scaling_figure( ...
            orbitIndex, ...
            radius_km, ...
            caseResults, ...
            fitNormal, ...
            fitPhase, ...
            fitClosure, ...
            fitBaseline, ...
            fitRho);


    fig2 = ...
        make_parent_phase_heatmap_figure( ...
            orbitIndex, ...
            radius_km, ...
            caseResults);


    fig3 = ...
        make_parent_normal_track_comparison_figure( ...
            orbitIndex, ...
            radius_km, ...
            caseResults);


    fig4 = ...
        make_parent_family_diagnostics_figure( ...
            orbitIndex, ...
            family, ...
            familyIdxSorted);


    %% --------------------------------------------------------
    %  3.8 Save parent figures
    %  --------------------------------------------------------

    parentFigureFiles = strings(4,1);

    if saveFigures

        parentFigureDir = ...
            fullfile( ...
                outputDir, ...
                sprintf('ParentRow_%03d_Figures',orbitIndex));

        if ~exist(parentFigureDir,'dir')
            mkdir(parentFigureDir);
        end

        parentFigureFiles(1) = ...
            save_study_figure( ...
                fig1, ...
                parentFigureDir, ...
                sprintf('Row_%03d_breakdown_scaling',orbitIndex), ...
                saveFigurePNG, ...
                figurePNGResolution, ...
                saveFigureFIG, ...
                saveFigurePDF);

        parentFigureFiles(2) = ...
            save_study_figure( ...
                fig2, ...
                parentFigureDir, ...
                sprintf('Row_%03d_phase_size_heatmaps',orbitIndex), ...
                saveFigurePNG, ...
                figurePNGResolution, ...
                saveFigureFIG, ...
                saveFigurePDF);

        parentFigureFiles(3) = ...
            save_study_figure( ...
                fig3, ...
                parentFigureDir, ...
                sprintf('Row_%03d_normal_track_comparison',orbitIndex), ...
                saveFigurePNG, ...
                figurePNGResolution, ...
                saveFigureFIG, ...
                saveFigurePDF);

        parentFigureFiles(4) = ...
            save_study_figure( ...
                fig4, ...
                parentFigureDir, ...
                sprintf('Row_%03d_continuation_diagnostics',orbitIndex), ...
                saveFigurePNG, ...
                figurePNGResolution, ...
                saveFigureFIG, ...
                saveFigurePDF);

    end


    %% --------------------------------------------------------
    %  3.9 Store parent result
    %  --------------------------------------------------------

    parentResult = struct();

    parentResult.orbitIndex = orbitIndex;

    parentResult.po = po;

    parentResult.cen = cen;

    parentResult.floquetGeom = floquetGeom;

    parentResult.family = family;

    parentResult.familyIdxAnalyzed = familyIdxSorted;

    parentResult.caseResults = caseResults;

    parentResult.fitNormal = fitNormal;
    parentResult.fitPhase = fitPhase;
    parentResult.fitClosure = fitClosure;
    parentResult.fitBaseline = fitBaseline;
    parentResult.fitRho = fitRho;

    parentResult.validity1deg = valid1;
    parentResult.validity5deg = valid5;

    % Store filenames only.  Do NOT store graphics handles in the MAT
    % file; doing so greatly inflates the MAT file and triggers MATLAB's
    % graphics-object warning.
    parentResult.figureFiles = parentFigureFiles;

    parentResults{ip} = parentResult;
    parentSucceeded(ip) = true;

end


%% ============================================================
%  4. COMPLETE CASE TABLE
%  ============================================================

caseTable = cell2table( ...
    allRows, ...
    'VariableNames',{ ...
        'ParentRow', ...
        'FamilyIndex', ...
        'TorusRadiusRMS_km', ...
        'RhoCycles', ...
        'RhoError_rad', ...
        'JacobiSpread', ...
        'NormalTrack_E50_deg', ...
        'NormalTrack_E95_deg', ...
        'NormalTrack_Emax_deg', ...
        'qA_MinFirstPeriod', ...
        'PhaseSpreadRMS_deg', ...
        'PeriodClosure_MedianRMS_deg', ...
        'BaselineRelError_MedianRMS', ...
        'MedianBaseline_km'});


disp(caseTable);


%% ============================================================
%  5. PARENT SUMMARY TABLE
%  ============================================================

successfulParentIdx = find(parentSucceeded);
nSuccessfulParents = numel(successfulParentIdx);

summaryRows = cell(nSuccessfulParents,16);

for jj = 1:nSuccessfulParents

    ip = successfulParentIdx(jj);

    p = parentResults{ip};

    [~,iLargest] = ...
        max(cellfun(@(x) x.sectionRadiusRMS_km,p.caseResults));

    qAMinLargest = ...
        p.caseResults{iLargest}.summary.qAMinFirst;

    summaryRows(jj,:) = { ...
        p.orbitIndex, ...
        p.floquetGeom.metrics.synodic.RMSExcursion_deg, ...
        p.floquetGeom.metrics.medianCircularity, ...
        p.floquetGeom.metrics.minCircularity, ...
        qAMinLargest, ...
        p.fitNormal.floor, ...
        p.fitNormal.p, ...
        p.fitPhase.p, ...
        p.fitClosure.p, ...
        p.fitBaseline.floor, ...
        p.fitBaseline.p, ...
        p.fitRho.p, ...
        p.validity1deg.radiusEstimate_km, ...
        p.validity1deg.lowerBound_km, ...
        p.validity5deg.radiusEstimate_km, ...
        p.validity5deg.lowerBound_km};

end


parentSummaryTable = cell2table( ...
    summaryRows, ...
    'VariableNames',{ ...
        'ParentRow', ...
        'FloquetNormalRMSExcursion_deg', ...
        'FloquetMedianCircularity_chi', ...
        'FloquetMinCircularity_chi', ...
        'qA_MinAtLargestAnalyzedTorus', ...
        'NormalErrorFloor_deg', ...
        'NormalNonlinearExponent_p', ...
        'PhaseSpreadExponent_p', ...
        'PeriodClosureNonlinearExponent_p', ...
        'BaselineErrorFloor', ...
        'BaselineNonlinearExponent_p', ...
        'RhoDepartureExponent_p', ...
        'EstimatedRadius_NormalError1deg_km', ...
        'LowerBoundRadius_NormalError1deg_km', ...
        'EstimatedRadius_NormalError5deg_km', ...
        'LowerBoundRadius_NormalError5deg_km'});


fprintf('\n');
fprintf('============================================================\n');
fprintf('PARENT BREAKDOWN SUMMARY\n');
fprintf('============================================================\n');

disp(parentSummaryTable);




%% ============================================================
%  5A. NORMAL-PLANE SUSCEPTIBILITY VERSUS FLOQUET CIRCULARITY
%  ============================================================

nSummaryParents = height(parentSummaryTable);

Kn_deg_per_km = nan(nSummaryParents,1);
nKnPoints = zeros(nSummaryParents,1);


for ip = 1:nSummaryParents

    parentRow = ...
        parentSummaryTable.ParentRow(ip);

    thisParent = ...
        caseTable.ParentRow == parentRow;


    R = ...
        caseTable.TorusRadiusRMS_km(thisParent);

    E50 = ...
        caseTable.NormalTrack_E50_deg(thisParent);


    E0 = ...
        parentSummaryTable.NormalErrorFloor_deg(ip);


    % Remove the fitted numerical floor before estimating the
    % finite-amplitude normal-error susceptibility.
    %
    % From
    %
    %   E50(R) = sqrt(E0^2 + E_nl(R)^2)
    %
    % recover
    %
    %   E_nl(R) = sqrt(E50^2 - E0^2).

    Enonlinear = ...
        sqrt( ...
            max( ...
                E50.^2 - E0.^2, ...
                0));


    % Restrict the coefficient estimate to the pre-breakdown regime.
    % This avoids allowing strongly nonlinear, near-90-deg cases to
    % determine what is intended to be a local susceptibility.
    useKn = ...
        isfinite(R) & ...
        isfinite(E50) & ...
        isfinite(Enonlinear) & ...
        R > 0 & ...
        E50 < 1.0 & ...
        Enonlinear > 0;


    nKnPoints(ip) = ...
        nnz(useKn);


    % Two points are allowed because row 294 currently has only two
    % analyzed cases below the 1-deg threshold.
    if nKnPoints(ip) >= 2

        Kn_deg_per_km(ip) = ...
            median( ...
                Enonlinear(useKn) ./ R(useKn));

    end

end


parentSummaryTable.NormalSusceptibility_Kn_deg_per_km = ...
    Kn_deg_per_km;

parentSummaryTable.NormalSusceptibility_NumPoints = ...
    nKnPoints;


%% Log-log dependence on minimum Floquet circularity

chiMin = ...
    parentSummaryTable.FloquetMinCircularity_chi;

normalExcursion_deg = ...
    parentSummaryTable.FloquetNormalRMSExcursion_deg;


useFit = ...
    isfinite(chiMin) & ...
    chiMin > 0 & ...
    isfinite(Kn_deg_per_km) & ...
    Kn_deg_per_km > 0;


xFit = ...
    log10(chiMin(useFit));

yFit = ...
    log10(Kn_deg_per_km(useFit));


pChi = ...
    polyfit( ...
        xFit, ...
        yFit, ...
        1);


chiExponent = ...
    pChi(1);

chiCoefficient = ...
    10^pChi(2);


yPred = ...
    polyval( ...
        pChi, ...
        xFit);


SSres = ...
    sum( ...
        (yFit-yPred).^2);

SStot = ...
    sum( ...
        (yFit-mean(yFit)).^2);

chiFitR2 = ...
    1 - SSres/SStot;


fprintf('\n');
fprintf('============================================================\n');
fprintf('FLOQUET CIRCULARITY / NORMAL-SUSCEPTIBILITY RELATION\n');
fprintf('============================================================\n');

fprintf( ...
    'K_n ~= %.6e * chi_min^(%.6f) deg/km\n', ...
    chiCoefficient, ...
    chiExponent);

fprintf( ...
    'log-log R^2 = %.6f\n', ...
    chiFitR2);


disp( ...
    parentSummaryTable(:,{ ...
        'ParentRow', ...
        'FloquetMinCircularity_chi', ...
        'FloquetNormalRMSExcursion_deg', ...
        'NormalSusceptibility_Kn_deg_per_km', ...
        'NormalSusceptibility_NumPoints'}));


%% Figure

figSusceptibility = figure( ...
    'Name','Floquet conditioning versus finite-amplitude susceptibility', ...
    'Color','w', ...
    'Position',[120 120 900 700]);


ax = axes(figSusceptibility);

hold(ax,'on');
grid(ax,'on');
box(ax,'on');


scatter( ...
    ax, ...
    chiMin(useFit), ...
    Kn_deg_per_km(useFit), ...
    90, ...
    normalExcursion_deg(useFit), ...
    'filled', ...
    'MarkerEdgeColor','k');


set( ...
    ax, ...
    'XScale','log', ...
    'YScale','log');


%% Fitted trend

chiPlot = ...
    logspace( ...
        log10(min(chiMin(useFit))), ...
        log10(max(chiMin(useFit))), ...
        300);


KnPlot = ...
    chiCoefficient .* ...
    chiPlot.^chiExponent;


plot( ...
    ax, ...
    chiPlot, ...
    KnPlot, ...
    'k--', ...
    'LineWidth',1.5, ...
    'DisplayName','log-log fit');


%% Parent-row labels

fitRows = ...
    find(useFit);


for ii = 1:numel(fitRows)

    ip = ...
        fitRows(ii);

    text( ...
        ax, ...
        1.06*chiMin(ip), ...
        Kn_deg_per_km(ip), ...
        sprintf('%d',parentSummaryTable.ParentRow(ip)), ...
        'FontSize',10, ...
        'VerticalAlignment','middle');

end


xlabel( ...
    ax, ...
    'Minimum Floquet circularity, $\chi_{\min}$', ...
    'Interpreter','latex');


ylabel( ...
    ax, ...
    'Normal susceptibility, $K_n$ [deg/km]', ...
    'Interpreter','latex');


title( ...
    ax, ...
    'Finite-amplitude plane sensitivity versus Floquet conditioning');


cb = colorbar(ax);

cb.Label.String = ...
    'Floquet-normal RMS excursion [deg]';


fitText = ...
    sprintf( ...
        ['$K_n \\approx %.2g\\,\\chi_{\\min}^{%.2f}$' ...
         '\n$R^2 = %.3f$'], ...
        chiCoefficient, ...
        chiExponent, ...
        chiFitR2);


text( ...
    ax, ...
    0.04, ...
    0.06, ...
    fitText, ...
    'Units','normalized', ...
    'Interpreter','latex', ...
    'FontSize',11, ...
    'VerticalAlignment','bottom', ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.5 0.5 0.5]);


%% Save with the rest of the study figures

susceptibilityFigureFile = "";

if saveFigures

    globalFigureDir = ...
        fullfile(outputDir,'Global_Figures');

    if ~exist(globalFigureDir,'dir')
        mkdir(globalFigureDir);
    end

    susceptibilityFigureFile = ...
        save_study_figure( ...
            figSusceptibility, ...
            globalFigureDir, ...
            'Global_Normal_Susceptibility_vs_Floquet_Circularity', ...
            saveFigurePNG, ...
            figurePNGResolution, ...
            saveFigureFIG, ...
            saveFigurePDF);

end

%% ============================================================
%  6. GLOBAL COMPARISON FIGURE
%  ============================================================

figGlobal = figure( ...
    'Name','Global Floquet breakdown comparison', ...
    'Color','w', ...
    'Position',[100 100 1500 650]);


tl = tiledlayout( ...
    figGlobal, ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


parentColors = ...
    lines(max(nSuccessfulParents,1));


%% ============================================================
%  LEFT PANEL: NORMAL-PLANE BREAKDOWN CURVES
%  ============================================================

ax1 = ...
    nexttile(tl);

hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');


allRLeft = [];
allELeft = [];


for jj = 1:nSuccessfulParents

    ip = ...
        successfulParentIdx(jj);

    p = ...
        parentResults{ip};


    R = ...
        cellfun( ...
            @(x) x.sectionRadiusRMS_km, ...
            p.caseResults);


    E = ...
        cellfun( ...
            @(x) x.summary.normalTrackE50_deg, ...
            p.caseResults);


    valid = ...
        isfinite(R) & ...
        isfinite(E) & ...
        R > 0 & ...
        E > 0;


    R = ...
        R(valid);

    E = ...
        E(valid);


    allRLeft = ...
        [allRLeft;R(:)]; %#ok<AGROW>

    allELeft = ...
        [allELeft;E(:)]; %#ok<AGROW>


    loglog( ...
        ax1, ...
        R, ...
        E, ...
        'o-', ...
        'LineWidth',1.15, ...
        'MarkerSize',5, ...
        'Color',parentColors(jj,:), ...
        'MarkerFaceColor',parentColors(jj,:), ...
        'DisplayName',sprintf( ...
            'row %d, $p=%.2f$', ...
            p.orbitIndex, ...
            p.fitNormal.p));

end


% Set explicitly so later graphics calls cannot accidentally return
% either axis to linear scaling.
set( ...
    ax1, ...
    'XScale','log', ...
    'YScale','log');


xlabel( ...
    ax1, ...
    'Corrected torus section RMS radius [km]');


ylabel( ...
    ax1, ...
    '$E_{50}$ normal-track error [deg]', ...
    'Interpreter','latex');


title( ...
    ax1, ...
    'Growth of finite-amplitude plane error');


legend( ...
    ax1, ...
    'Location','northwest', ...
    'NumColumns',2, ...
    'Interpreter','latex', ...
    'FontSize',9);


if ~isempty(allRLeft)

    xlim( ...
        ax1, ...
        [ ...
            0.8*min(allRLeft), ...
            1.25*max(allRLeft) ...
        ]);

end


if ~isempty(allELeft)

    ylim( ...
        ax1, ...
        [ ...
            0.6*min(allELeft), ...
            1.4*max(allELeft) ...
        ]);

end


%% ============================================================
%  RIGHT PANEL: FLOQUET-SURROGATE VALIDITY RADII
%  ============================================================

ax2 = ...
    nexttile(tl);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');


rows = ...
    parentSummaryTable.ParentRow;


R1_est = ...
    parentSummaryTable.EstimatedRadius_NormalError1deg_km;

R1_lb = ...
    parentSummaryTable.LowerBoundRadius_NormalError1deg_km;


R5_est = ...
    parentSummaryTable.EstimatedRadius_NormalError5deg_km;

R5_lb = ...
    parentSummaryTable.LowerBoundRadius_NormalError5deg_km;


% True only when an actual threshold crossing was found.
has1 = ...
    isfinite(R1_est);

has5 = ...
    isfinite(R5_est);


% When no threshold crossing occurred, plot the largest tested radius
% as a lower bound instead.
R1plot = ...
    R1_est;

R1plot(~has1) = ...
    R1_lb(~has1);


R5plot = ...
    R5_est;

R5plot(~has5) = ...
    R5_lb(~has5);


nParentsPlot = ...
    numel(rows);


y = ...
    (1:nParentsPlot).';


% Separate the two criteria vertically for each parent.
dy = ...
    0.13;

y1 = ...
    y - dy;

y5 = ...
    y + dy;


% Use fixed criterion colors so color has a single meaning.
criterionColors = ...
    lines(2);

color1 = ...
    criterionColors(1,:);

color5 = ...
    criterionColors(2,:);


%% Connect actual 1-deg and 5-deg crossings

bothFinite = ...
    has1 & has5;


for k = find(bothFinite).'

    plot( ...
        ax2, ...
        [R1plot(k),R5plot(k)], ...
        [y(k),y(k)], ...
        '-', ...
        'Color',[0.60 0.60 0.60], ...
        'LineWidth',1.0, ...
        'HandleVisibility','off');

end


%% 1-degree criterion: actual crossings

plot( ...
    ax2, ...
    R1plot(has1), ...
    y1(has1), ...
    'o', ...
    'Color',color1, ...
    'MarkerFaceColor',color1, ...
    'MarkerSize',7.5, ...
    'LineWidth',1.3, ...
    'DisplayName','$E_{50}=1^\circ$ crossing');


%% 1-degree criterion: threshold not reached

plot( ...
    ax2, ...
    R1plot(~has1), ...
    y1(~has1), ...
    '>', ...
    'Color',color1, ...
    'MarkerFaceColor','none', ...
    'MarkerSize',8.5, ...
    'LineWidth',1.4, ...
    'DisplayName','$E_{50}<1^\circ$ through tested range');


%% 5-degree criterion: actual crossings

plot( ...
    ax2, ...
    R5plot(has5), ...
    y5(has5), ...
    's', ...
    'Color',color5, ...
    'MarkerFaceColor',color5, ...
    'MarkerSize',7.5, ...
    'LineWidth',1.3, ...
    'DisplayName','$E_{50}=5^\circ$ crossing');


%% 5-degree criterion: threshold not reached

plot( ...
    ax2, ...
    R5plot(~has5), ...
    y5(~has5), ...
    '>', ...
    'Color',color5, ...
    'MarkerFaceColor','none', ...
    'MarkerSize',8.5, ...
    'LineWidth',1.4, ...
    'DisplayName','$E_{50}<5^\circ$ through tested range');


%% Right-panel formatting

set( ...
    ax2, ...
    'XScale','log', ...
    'YTick',y, ...
    'YTickLabel',string(rows), ...
    'YDir','reverse');


xlabel( ...
    ax2, ...
    'Corrected torus section RMS radius [km]');


ylabel( ...
    ax2, ...
    'JPL parent row');


title( ...
    ax2, ...
    'Floquet-plane validity radius');


legend( ...
    ax2, ...
    'Location','best', ...
    'Interpreter','latex', ...
    'FontSize',9);


allRRight = ...
    [ ...
        R1plot(:); ...
        R5plot(:) ...
    ];


allRRight = ...
    allRRight( ...
        isfinite(allRRight) & ...
        allRRight > 0);


if ~isempty(allRRight)

    xlim( ...
        ax2, ...
        [ ...
            0.7*min(allRRight), ...
            1.5*max(allRRight) ...
        ]);

end


ylim( ...
    ax2, ...
    [ ...
        0.4, ...
        nParentsPlot+0.6 ...
    ]);


%% ============================================================
%  OVERALL TITLE
%  ============================================================

title( ...
    tl, ...
    ['Finite-amplitude breakdown and validity of the ', ...
     'Floquet-plane surrogate']);


%% ============================================================
%  SAVE
%  ============================================================

globalFigureFile = "";


if saveFigures

    globalFigureDir = ...
        fullfile( ...
            outputDir, ...
            'Global_Figures');


    if ~exist(globalFigureDir,'dir')

        mkdir(globalFigureDir);

    end


    globalFigureFile = ...
        save_study_figure( ...
            figGlobal, ...
            globalFigureDir, ...
            'Global_Floquet_Breakdown_Comparison', ...
            saveFigurePNG, ...
            figurePNGResolution, ...
            saveFigureFIG, ...
            saveFigurePDF);

end

%% ============================================================
%  6A. FAILED-PARENT SUMMARY
%  ============================================================

failedParentIdx = find(~parentSucceeded);

failedParentTable = table( ...
    parentRows(failedParentIdx).', ...
    parentFailureMessage(failedParentIdx), ...
    'VariableNames',{ ...
        'ParentRow', ...
        'FailureMessage'});

if ~isempty(failedParentIdx)

    fprintf('\n');
    fprintf('Parents skipped after strict startup / continuation failure:\n');
    disp(failedParentTable);

end


%% ============================================================
%  7. SAVE
%  ============================================================

if saveResults

    writetable( ...
        failedParentTable, ...
        fullfile( ...
            outputDir, ...
            'QPO_Floquet_Normal_Breakdown_FailedParents.csv'));


    writetable( ...
        caseTable, ...
        fullfile( ...
            outputDir, ...
            'QPO_Floquet_Normal_Breakdown_Cases.csv'));


    writetable( ...
        parentSummaryTable, ...
        fullfile( ...
            outputDir, ...
            'QPO_Floquet_Normal_Breakdown_ParentSummary.csv'));


    save( ...
        fullfile( ...
            outputDir, ...
            'QPO_Floquet_Normal_Breakdown_Study.mat'), ...
        'parentResults', ...
        'caseTable', ...
        'parentSummaryTable', ...
        'parentRows', ...
        'parentSucceeded', ...
        'parentFailureMessage', ...
        'failedParentTable', ...
        'KSeeds', ...
        'nContinuationSteps', ...
        'continuationStepMultiplier', ...
        'nSmallMembersToAlwaysAnalyze', ...
        'globalFigureFile', ...
        'saveFigures', ...
        'saveFigurePNG', ...
        'figurePNGResolution', ...
        'saveFigureFIG', ...
        'saveFigurePDF', ...
        '-v7.3');

end


%% ============================================================
%  8. INTERPRETATION GUIDE
%  ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('INTERPRETATION GUIDE\n');
fprintf('============================================================\n');

fprintf([ ...
    'NormalTrack_E50_deg is the primary typical-phase surrogate error.\n', ...
    'For each common collector phase it computes the RMS finite-QPO versus\n', ...
    'Floquet normal-track error over the first parent period; E50 is the\n', ...
    'median of those per-phase RMS errors.  E95 and Emax summarize the same\n', ...
    'per-phase RMS quantity at the 95th percentile and worst phase.\n\n']);

fprintf([ ...
    'PhaseSpreadRMS_deg is zero in the exact linear model.  Its reported\n', ...
    'power law is fit only on the resolved rising branch after the observed\n', ...
    'small-radius numerical minimum.\n\n']);

fprintf([ ...
    'PeriodClosure_MedianRMS_deg is also zero in the exact linear model.\n', ...
    'Its reported power law likewise uses only the resolved rising branch,\n', ...
    'so tiny propagation/differencing outliers are not treated as physics.\n\n']);

fprintf([ ...
    'The raw normal comparison contains a parent-dependent numerical floor.\n', ...
    'The reported normal exponent therefore comes from the floor-aware model\n', ...
    '  E(R)=sqrt(E_floor^2 + (C R^p)^2).\n', ...
    'This separates the asymptotic nonlinear growth from interpolation /\n', ...
    'discretization error that does not vanish over the tested small sizes.\n\n']);

fprintf([ ...
    'The finite QPO is propagated for TWO parent periods.  The primary\n', ...
    'Floquet-normal error uses only the first period; the second period is\n', ...
    'used to measure one-period plane non-closure.\n\n']);

fprintf([ ...
    'The family is generated by pseudo-arclength continuation.  The plotted\n', ...
    'independent variable is the actual corrected torus RMS radius, never the\n', ...
    'seed amplitude K.\n']);

fprintf('============================================================\n');


%% ========================================================================
%  LOCAL FUNCTIONS
%  ========================================================================


function idx = unique_equal_phase_start_indices(N,nCollectors)

    canonicalSets = zeros(N,nCollectors);

    for k = 1:N

        j = qpo_equal_phase_indices(N,nCollectors,k);

        canonicalSets(k,:) = sort(j(:).');

    end

    [~,idx] = unique(canonicalSets,'rows','stable');

    idx = idx(:).';

end


function idx = choose_radius_distributed_members( ...
    radius_km,maxMembers,nSmallAlways)

    valid = ...
        find( ...
            isfinite(radius_km) & ...
            radius_km > 0);


    if isempty(valid)

        error('No valid positive-radius family members.');

    end


    [rSorted,order] = ...
        sort(radius_km(valid));


    idxSorted = ...
        valid(order);


    nSmallAlways = ...
        min(nSmallAlways,numel(idxSorted));


    mustKeep = ...
        idxSorted(1:nSmallAlways);


    if numel(idxSorted) <= maxMembers

        idx = idxSorted(:).';
        return

    end


    nRemaining = ...
        maxMembers-numel(mustKeep);


    if nRemaining <= 0

        idx = mustKeep(:).';
        return

    end


    rMin = ...
        rSorted(nSmallAlways);

    rMax = ...
        max(rSorted);


    if rMax/rMin >= 3

        targetR = ...
            logspace( ...
                log10(rMin), ...
                log10(rMax), ...
                nRemaining+1);

    else

        targetR = ...
            linspace( ...
                rMin, ...
                rMax, ...
                nRemaining+1);

    end


    targetR = ...
        targetR(2:end);


    extra = zeros(1,numel(targetR));

    for k = 1:numel(targetR)

        [~,j] = ...
            min(abs(rSorted-targetR(k)));

        extra(k) = ...
            idxSorted(j);

    end


    idx = ...
        unique( ...
            [mustKeep(:).',extra,idxSorted(end)], ...
            'stable');

end


function fit = fit_local_power_law( ...
    R,E,errorCeiling,maxPoints,minPoints)

    R = R(:);
    E = E(:);


    valid = ...
        isfinite(R) & ...
        R > 0 & ...
        isfinite(E) & ...
        E > 1e-10;


    idx = ...
        find(valid & E <= errorCeiling);


    if numel(idx) < minPoints

        idx = ...
            find(valid);

    end


    if isempty(idx)

        fit = empty_power_fit();
        return

    end


    [~,sortIdx] = ...
        sort(R(idx));


    idx = ...
        idx(sortIdx);


    idx = ...
        idx(1:min(maxPoints,numel(idx)));


    if numel(idx) < minPoints

        fit = empty_power_fit();
        fit.indices = idx;
        return

    end


    p = ...
        polyfit( ...
            log(R(idx)), ...
            log(E(idx)), ...
            1);


    fit = struct();

    fit.p = p(1);
    fit.C = exp(p(2));

    fit.indices = idx;

    fit.R = R(idx);
    fit.E = E(idx);

    fit.Efit = ...
        fit.C*fit.R.^fit.p;

end



function fit = fit_post_floor_power_law( ...
    R,E,errorCeiling,maxPoints,minPoints)
%FIT_POST_FLOOR_POWER_LAW
% Fit E = C R^p on the resolved rising branch after the numerical floor.

    R = R(:);
    E = E(:);

    valid = ...
        isfinite(R) & R > 0 & ...
        isfinite(E) & E > 0;

    if isfinite(errorCeiling)

        valid = ...
            valid & ...
            E <= errorCeiling;

    end

    idxAll = find(valid);

    if numel(idxAll) < minPoints

        fit = empty_power_fit();
        return

    end

    [~,ord] = sort(R(idxAll));
    idxAll = idxAll(ord);

    [~,iMinLocal] = min(E(idxAll));

    idx = ...
        idxAll(iMinLocal:end);

    if numel(idx) < minPoints

        fit = empty_power_fit();
        fit.indices = idx;
        return

    end

    idx = ...
        idx(1:min(maxPoints,numel(idx)));

    p = ...
        polyfit( ...
            log(R(idx)), ...
            log(E(idx)), ...
            1);

    fit = struct();

    fit.p = p(1);
    fit.C = exp(p(2));

    fit.indices = idx;
    fit.R = R(idx);
    fit.E = E(idx);
    fit.Efit = fit.C*fit.R.^fit.p;

end


function fit = empty_power_fit()

    fit = struct();

    fit.p = NaN;
    fit.C = NaN;

    fit.indices = [];
    fit.R = [];
    fit.E = [];
    fit.Efit = [];

end


function fit = fit_floor_power_law( ...
    R,E,errorCeiling,maxPoints,minPoints)
%FIT_FLOOR_POWER_LAW
%
% Fit
%
%   E(R) = sqrt(E_floor^2 + (C R^p)^2)
%
% in log-error space.  All three fitted quantities are constrained positive
% by optimizing their logarithms.

    R = R(:);
    E = E(:);

    valid = ...
        isfinite(R) & ...
        R > 0 & ...
        isfinite(E) & ...
        E > 0;

    if isfinite(errorCeiling)

        valid = ...
            valid & ...
            E <= errorCeiling;

    end

    idx = find(valid);

    if numel(idx) < minPoints

        idx = find( ...
            isfinite(R) & R > 0 & ...
            isfinite(E) & E > 0);

    end

    if isempty(idx)

        fit = empty_floor_fit();
        return

    end

    [~,ord] = sort(R(idx));
    idx = idx(ord);

    idx = ...
        idx(1:min(maxPoints,numel(idx)));

    if numel(idx) < minPoints

        fit = empty_floor_fit();
        fit.indices = idx;
        return

    end

    Rf = R(idx);
    Ef = E(idx);

    floor0 = ...
        max(0.8*min(Ef),realmin);

    nonlinearTop = ...
        sqrt( ...
            max( ...
                max(Ef)^2-floor0^2, ...
                (0.1*max(Ef))^2));

    C0 = ...
        max( ...
            nonlinearTop/max(Rf), ...
            realmin);

    p0 = 1.0;

    theta0 = ...
        log([floor0,C0,p0]);

    objective = ...
        @(theta) floor_power_objective(theta,Rf,Ef);

    options = optimset( ...
        'Display','off', ...
        'TolX',1e-10, ...
        'TolFun',1e-12, ...
        'MaxIter',2000, ...
        'MaxFunEvals',5000);

    theta = ...
        fminsearch( ...
            objective, ...
            theta0, ...
            options);

    pars = exp(theta);

    fit = struct();

    fit.floor = pars(1);
    fit.C = pars(2);
    fit.p = pars(3);

    fit.indices = idx;
    fit.R = Rf;
    fit.E = Ef;

    fit.Efit = ...
        floor_power_model( ...
            fit.floor, ...
            fit.C, ...
            fit.p, ...
            fit.R);

    fit.nonlinearComponent = ...
        fit.C*fit.R.^fit.p;

end


function J = floor_power_objective(theta,R,E)

    pars = exp(theta);

    Epred = ...
        floor_power_model( ...
            pars(1), ...
            pars(2), ...
            pars(3), ...
            R);

    residual = ...
        log(Epred)-log(E);

    J = ...
        sum(residual.^2);

end


function E = floor_power_model(Efloor,C,p,R)

    E = ...
        sqrt( ...
            Efloor.^2 + ...
            (C.*R.^p).^2);

end


function fit = empty_floor_fit()

    fit = struct();

    fit.floor = NaN;
    fit.C = NaN;
    fit.p = NaN;

    fit.indices = [];
    fit.R = [];
    fit.E = [];
    fit.Efit = [];
    fit.nonlinearComponent = [];

end


function result = estimate_error_threshold(R,E,tol)
%ESTIMATE_ERROR_THRESHOLD
% If the sampled curve crosses tol, interpolate in log(R)-log(E) between
% the first bracketing pair.  Otherwise return the largest tested acceptable
% radius as a lower bound.

    R = R(:);
    E = E(:);

    valid = ...
        isfinite(R) & ...
        R > 0 & ...
        isfinite(E) & ...
        E >= 0;

    R = R(valid);
    E = E(valid);

    [R,ord] = sort(R);
    E = E(ord);

    result = struct();

    result.tolerance = tol;
    result.crossed = false;
    result.radiusEstimate_km = NaN;
    result.lowerBound_km = NaN;

    if isempty(R)
        return
    end

    below = E <= tol;

    if any(below)

        result.lowerBound_km = ...
            max(R(below));

    end

    iCross = ...
        find(E > tol,1,'first');

    if isempty(iCross)

        % No observed crossing: the largest tested acceptable radius is only
        % a lower bound on the actual validity limit.
        return

    end

    if iCross == 1

        result.crossed = true;
        result.radiusEstimate_km = R(1);
        return

    end

    i0 = iCross-1;

    if E(i0) <= 0 || E(iCross) <= 0

        Rcross = ...
            interp1( ...
                E([i0,iCross]), ...
                R([i0,iCross]), ...
                tol);

    else

        logR = ...
            interp1( ...
                log(E([i0,iCross])), ...
                log(R([i0,iCross])), ...
                log(tol));

        Rcross = exp(logR);

    end

    result.crossed = true;
    result.radiusEstimate_km = Rcross;

end


function print_threshold_result(label,result)

    if result.crossed

        fprintf('  estimated R at median normal error = %s : %.6g km\\n', ...
            label, ...
            result.radiusEstimate_km);

    else

        fprintf(['  median normal error never reached %s; ', ...
                 'validity radius > %.6g km (tested lower bound)\\n'], ...
            label, ...
            result.lowerBound_km);

    end

end


function Rmax = largest_radius_below_error(R,E,tolDeg)

    valid = ...
        isfinite(R) & ...
        isfinite(E) & ...
        E <= tolDeg;


    if any(valid)

        Rmax = max(R(valid));

    else

        Rmax = NaN;

    end

end


function fig = make_parent_error_scaling_figure( ...
    orbitIndex,R,cases,fitNormal,fitPhase,fitClosure,fitBaseline,fitRho)

    n = numel(cases);

    normalMedian = nan(n,1);
    normalWorst = nan(n,1);

    phaseSpread = nan(n,1);

    closureMedian = nan(n,1);

    baselineMedian = nan(n,1);

    rhoError = nan(n,1);


    for k = 1:n

        c = cases{k};

        normalMedian(k) = ...
            c.summary.floquetErrorFirstMedianRMS_deg;

        normalWorst(k) = ...
            c.summary.floquetErrorFirstWorstRMS_deg;

        phaseSpread(k) = ...
            c.phaseSpreadRMS_deg;

        closureMedian(k) = ...
            c.summary.periodClosureMedianRMS_deg;

        baselineMedian(k) = ...
            c.summary.baselineRelErrorMedianRMS;

        rhoError(k) = ...
            c.rhoError_rad;

    end


    fig = figure( ...
        'Name',sprintf('Row %d Floquet breakdown scaling',orbitIndex), ...
        'Color','w', ...
        'Position',[100 100 1450 850]);


    tl = tiledlayout( ...
        fig, ...
        2,2, ...
        'TileSpacing','compact', ...
        'Padding','compact');


    ax = nexttile(tl);

    loglog(ax,R,normalMedian,'o-','DisplayName','$E_{50}$');
    hold(ax,'on');
    grid(ax,'on');

    loglog(ax,R,normalWorst,'s--','DisplayName','$E_{\max}$');

    if isfinite(fitNormal.p)

        loglog( ...
            ax, ...
            fitNormal.R, ...
            fitNormal.Efit, ...
            'k:', ...
            'LineWidth',2, ...
            'DisplayName',sprintf( ...
                'floor-aware $p=%.2f$', ...
                fitNormal.p));

        yline( ...
            ax, ...
            fitNormal.floor, ...
            'k--', ...
            sprintf('$E_0=%.3g^\\circ$',fitNormal.floor), ...
            'HandleVisibility','off');

    end

    xlabel(ax,'Torus RMS radius [km]');
    ylabel(ax,'RMS normal error [deg]');

    title(ax,'Finite QPO versus Floquet plane');

    legend(ax,'Location','best');


    ax = nexttile(tl);

    loglog(ax,R,phaseSpread,'o','DisplayName','phase spread');
    hold(ax,'on');
    grid(ax,'on');

    loglog(ax,R,closureMedian,'s','DisplayName','period non-closure');

    if ~isempty(fitPhase.indices)

        loglog( ...
            ax, ...
            R(fitPhase.indices), ...
            phaseSpread(fitPhase.indices), ...
            '-', ...
            'HandleVisibility','off');

    end

    if ~isempty(fitClosure.indices)

        loglog( ...
            ax, ...
            R(fitClosure.indices), ...
            closureMedian(fitClosure.indices), ...
            '-', ...
            'HandleVisibility','off');

    end

    if isfinite(fitPhase.p)

        loglog( ...
            ax, ...
            fitPhase.R, ...
            fitPhase.Efit, ...
            'k:', ...
            'LineWidth',1.8, ...
            'DisplayName',sprintf('phase $R^{%.2f}$',fitPhase.p));

    end

    if isfinite(fitClosure.p)

        loglog( ...
            ax, ...
            fitClosure.R, ...
            fitClosure.Efit, ...
            'k--', ...
            'LineWidth',1.8, ...
            'DisplayName',sprintf('closure $R^{%.2f}$',fitClosure.p));

    end

    xlabel(ax,'Torus RMS radius [km]');
    ylabel(ax,'Angular nonlinearity [deg]');

    title(ax,'Effects absent from the linear model');

    legend(ax,'Location','best');


    ax = nexttile(tl);

    loglog(ax,R,baselineMedian,'o-','DisplayName','measured');

    hold(ax,'on');
    grid(ax,'on');

    if isfinite(fitBaseline.p)

        loglog( ...
            ax, ...
            fitBaseline.R, ...
            fitBaseline.Efit, ...
            'k:', ...
            'LineWidth',2, ...
            'DisplayName',sprintf( ...
                'floor-aware $p=%.2f$', ...
                fitBaseline.p));

        yline( ...
            ax, ...
            fitBaseline.floor, ...
            'k--', ...
            'HandleVisibility','off');

        legend(ax,'Location','best');

    end

    xlabel(ax,'Torus RMS radius [km]');
    ylabel(ax,'RMS relative baseline error');

    title(ax,'Breakdown of linear baseline breathing');


    ax = nexttile(tl);

    loglog(ax,R,rhoError,'o','DisplayName','measured');

    hold(ax,'on');
    grid(ax,'on');

    if ~isempty(fitRho.indices)

        loglog( ...
            ax, ...
            R(fitRho.indices), ...
            rhoError(fitRho.indices), ...
            '-', ...
            'HandleVisibility','off');

    end

    if isfinite(fitRho.p)

        loglog( ...
            ax, ...
            fitRho.R, ...
            fitRho.Efit, ...
            'k:', ...
            'LineWidth',2, ...
            'DisplayName',sprintf('$p=%.2f$',fitRho.p));

        legend(ax,'Location','best');

    end

    xlabel(ax,'Torus RMS radius [km]');
    ylabel(ax,'$|\Delta\rho|$ [rad]');

    title(ax,'Nonlinear rotation-number departure');


    title( ...
        tl, ...
        sprintf( ...
            'Parent row %d: finite-amplitude breakdown of Floquet surrogate', ...
            orbitIndex));

end


function fig = make_parent_phase_heatmap_figure( ...
    orbitIndex,R,cases)

    nSizes = numel(cases);

    phaseIndices = ...
        cases{1}.phaseStartIndices;


    nPhases = numel(phaseIndices);


    E = nan(nSizes,nPhases);
    C = nan(nSizes,nPhases);


    for is = 1:nSizes

        E(is,:) = ...
            cases{is}.floquetErrorFirstRMS_deg(:).';

        C(is,:) = ...
            cases{is}.periodClosureRMS_deg(:).';

    end


    fig = figure( ...
        'Name',sprintf('Row %d phase-size breakdown',orbitIndex), ...
        'Color','w', ...
        'Position',[110 110 1400 600]);


    tl = tiledlayout( ...
        fig, ...
        1,2, ...
        'TileSpacing','compact', ...
        'Padding','compact');


    ax = nexttile(tl);

    imagesc( ...
        ax, ...
        phaseIndices, ...
        1:nSizes, ...
        E);

    set(ax,'YDir','normal');

    xlabel(ax,'Phase start index');
    ylabel(ax,'Finite-QPO size case');

    yticks(ax,1:nSizes);
    yticklabels(ax,compose('%.3g km',R));

    title(ax,'RMS Floquet-normal error [deg]');

    colorbar(ax);


    ax = nexttile(tl);

    imagesc( ...
        ax, ...
        phaseIndices, ...
        1:nSizes, ...
        C);

    set(ax,'YDir','normal');

    xlabel(ax,'Phase start index');
    ylabel(ax,'Finite-QPO size case');

    yticks(ax,1:nSizes);
    yticklabels(ax,compose('%.3g km',R));

    title(ax,'One-period plane non-closure [deg]');

    colorbar(ax);


    title( ...
        tl, ...
        sprintf( ...
            'Parent row %d: emergence of nonlinear phase dependence', ...
            orbitIndex));

end


function fig = make_parent_normal_track_comparison_figure( ...
    orbitIndex,R,cases)

    n = numel(cases);

    idxShow = unique(round(linspace(1,n,min(3,n))));

    nShow = numel(idxShow);


    fig = figure( ...
        'Name',sprintf('Row %d normal-track comparisons',orbitIndex), ...
        'Color','w', ...
        'Position',[100 100 1550 520]);


    tl = tiledlayout( ...
        fig, ...
        1,nShow, ...
        'TileSpacing','compact', ...
        'Padding','compact');


    [xs,ys,zs] = sphere(28);


    for j = 1:nShow

        is = idxShow(j);

        c = cases{is};

        tr = c.referencePhaseTrack;


        ax = nexttile(tl);

        surf( ...
            ax, ...
            xs,ys,zs, ...
            'FaceColor',[0.8 0.8 0.8], ...
            'FaceAlpha',0.05, ...
            'EdgeColor',[0.75 0.75 0.75], ...
            'EdgeAlpha',0.15, ...
            'HandleVisibility','off');

        hold(ax,'on');
        grid(ax,'on');
        axis(ax,'equal');


        plot3( ...
            ax, ...
            tr.nFloquet(:,1), ...
            tr.nFloquet(:,2), ...
            tr.nFloquet(:,3), ...
            'k--', ...
            'LineWidth',2, ...
            'DisplayName','Floquet');


        plot3( ...
            ax, ...
            tr.nQPO(:,1), ...
            tr.nQPO(:,2), ...
            tr.nQPO(:,3), ...
            'LineWidth',1.6, ...
            'DisplayName','finite QPO');


        xlabel(ax,'$n_x$');
        ylabel(ax,'$n_y$');
        zlabel(ax,'$n_z$');

        view(ax,35,25);


        title(ax,sprintf( ...
            '$R_{\\rm rms}=%.3g$ km, RMS error %.3g$^\\circ$', ...
            R(is), ...
            c.floquetErrorFirstRMS_deg(1)));


        if j == 1
            legend(ax,'Location','best');
        end

    end


    title( ...
        tl, ...
        sprintf( ...
            'Parent row %d: linear Floquet plane versus finite-QPO plane', ...
            orbitIndex));

end


function fig = make_parent_family_diagnostics_figure( ...
    orbitIndex,family,idxAnalyzed)

    n = numel(family.radiusRMS_km);


    fig = figure( ...
        'Name',sprintf('Row %d continuation family diagnostics',orbitIndex), ...
        'Color','w', ...
        'Position',[120 120 1350 560]);


    tl = tiledlayout( ...
        fig, ...
        1,2, ...
        'TileSpacing','compact', ...
        'Padding','compact');


    ax = nexttile(tl);

    plot( ...
        ax, ...
        1:n, ...
        family.radiusRMS_km, ...
        'o-');

    hold(ax,'on');
    grid(ax,'on');

    invalidFamily = ...
        ~family.analysisValid;

    if any(invalidFamily)

        plot( ...
            ax, ...
            find(invalidFamily), ...
            family.radiusRMS_km(invalidFamily), ...
            'x', ...
            'MarkerSize',9, ...
            'LineWidth',1.5, ...
            'DisplayName','excluded: unresolved');

    end

    scatter( ...
        ax, ...
        idxAnalyzed, ...
        family.radiusRMS_km(idxAnalyzed), ...
        70, ...
        'filled');

    xlabel(ax,'Continuation family index');
    ylabel(ax,'Corrected section RMS radius [km]');

    title(ax,'Physical amplitude along PALC family');


    ax = nexttile(tl);

    semilogy( ...
        ax, ...
        family.radiusRMS_km, ...
        max(family.jacobiSpread,eps), ...
        'o-');

    hold(ax,'on');
    grid(ax,'on');

    yline( ...
        ax, ...
        family.jacobiLimit, ...
        'k--', ...
        'analysis limit', ...
        'HandleVisibility','off');

    xlabel(ax,'Corrected section RMS radius [km]');
    ylabel(ax,'Jacobi spread across section');

    title(ax,'Invariant-curve physical consistency');


    title( ...
        tl, ...
        sprintf( ...
            'Parent row %d: finite-QPO continuation diagnostics', ...
            orbitIndex));

end


function primaryPath = save_study_figure( ...
    fig,folder,baseName,savePNG,pngResolution,saveFIG,savePDF)
%SAVE_STUDY_FIGURE Save one study figure without embedding graphics
% handles in the MAT results structure.
%
% Returns the primary saved path (PNG when enabled, otherwise FIG/PDF).

    primaryPath = "";

    if savePNG

        pngPath = ...
            fullfile(folder,[baseName,'.png']);

        exportgraphics( ...
            fig, ...
            pngPath, ...
            'Resolution',pngResolution);

        primaryPath = string(pngPath);

    end


    if saveFIG

        figPath = ...
            fullfile(folder,[baseName,'.fig']);

        savefig(fig,figPath);

        if strlength(primaryPath)==0
            primaryPath = string(figPath);
        end

    end


    if savePDF

        pdfPath = ...
            fullfile(folder,[baseName,'.pdf']);

        exportgraphics( ...
            fig, ...
            pdfPath, ...
            'ContentType','vector');

        if strlength(primaryPath)==0
            primaryPath = string(pdfPath);
        end

    end

end
