%% RUN_JPL_Halo_Floquet_Geometry_Survey
%
% FINESST / GMOS
% Linear Floquet predictor of three-collector QPO formation morphology.
%
% Scientific question
% -------------------
% Can we predict the essential formation behavior directly from the parent
% periodic orbit's center Floquet mode, before generating a finite-amplitude
% QPO?
%
% For every catalog orbit with a genuine nontrivial center pair, this script
% transports the selected complex Floquet eigenvector around one parent
% period:
%
%       w(t) = Phi(t,0) w0.
%
% Writing the position component as
%
%       w_r(t) = a(t) + i b(t),
%
% the first-order center ellipse is
%
%       delta r(t,theta)
%       = a(t) cos(theta) - b(t) sin(theta).
%
% This immediately gives:
%
%       Floquet plane normal:
%           n_F ~ a x b
%
%       ellipse circularity:
%           chi = sigma_2/sigma_1
%
%       position RMS scale:
%           R_F = ||[a,-b]||_F/sqrt(2)
%
% and, for three equal-phase collectors separated by 120 deg,
%
%       B_RMS = sqrt(3) R_F
%
% exactly in the linearized model.
%
% The survey therefore produces a small set of physically interpretable
% predictors:
%
%   Normal excursion       -> pointing / accessibility morphology
%   Ellipse circularity    -> sensitivity to common collector phase
%   Position breathing     -> baseline-scale variation around the PO
%   rho0/(2pi)             -> center-phase advance per parent period
%
% Importantly, these quantities are independent of arbitrary Floquet
% eigenvector phase and, except for absolute R_F, independent of eigenvector
% normalization.
%
% Required existing FINESST functions
% -----------------------------------
%   monodromy_CR3BP
%   gmos_center_eigpair_from_eigs
%   STM_vec
%
% New helper
% ----------
%   transport_floquet_center_geometry_CR3BP
%
% This is a LINEAR predictor study. It does not generate GMOS tori and does
% not run interferometric imaging.  The next validation step is to compare
% these predicted normal tracks with small finite-amplitude QPO formations.

clear;
clc;
close all;


%% ============================================================
%  0. PLOT DEFAULTS
%  ============================================================

set(groot,'DefaultTextInterpreter','latex');
set(groot,'DefaultAxesTickLabelInterpreter','latex');
set(groot,'DefaultLegendInterpreter','latex');

set(groot,'DefaultAxesFontSize',14);
set(groot,'DefaultTextFontSize',16);

set(groot,'DefaultFigureColor','w');
set(groot,'DefaultAxesColor','w');
set(groot,'DefaultAxesXColor','k');
set(groot,'DefaultAxesYColor','k');
set(groot,'DefaultTextColor','k');


%% ============================================================
%  1. CONFIGURATION
%  ============================================================

catalogFile = ...
    'L1_northern_halo_orbits_JPL_IC_Earth_Moon.csv';


% Prefer the clean Floquet-survey output generated by the preceding study.
summaryFileCandidates = { ...
    fullfile( ...
        pwd, ...
        'JPL_Halo_Floquet_Survey', ...
        'JPL_Halo_Floquet_Summary.csv'), ...
    fullfile( ...
        pwd, ...
        'JPL_Halo_Floquet_Summary.csv')};


summaryFile = '';

for k = 1:numel(summaryFileCandidates)

    if isfile(summaryFileCandidates{k})

        summaryFile = ...
            summaryFileCandidates{k};

        break

    end

end


if isempty(summaryFile)

    error( ...
        ['Could not find JPL_Halo_Floquet_Summary.csv. ', ...
         'Run the cleaned whole-family Floquet survey first.']);

end


% Floquet-center selection.
centerMode = 'vertical';

centerOpts = struct();
centerOpts.tolUnit = 1e-6;
centerOpts.tolImag = 1e-10;
centerOpts.warnMismatch = false;


% One parent period is sufficient because the transported Floquet plane
% closes after one period up to the center rotation exp(i*rho0).
nTimeSamples = 401;


% Common center phases used only to measure the linearized triangle-shape
% sensitivity inside each instantaneous center ellipse.
nPhaseSamples = 61;


odeOpts = odeset( ...
    'RelTol',1e-12, ...
    'AbsTol',1e-12);


useParallel = true;


% Representative rows from the earlier morphology studies.
highlightRows = [40 82 125 197 294 296];


saveResults = true;

outputDir = fullfile( ...
    pwd, ...
    'JPL_Halo_Floquet_Geometry_Survey');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end


%% ============================================================
%  2. READ CATALOG + CLEAN FLOQUET INVENTORY
%  ============================================================

catalogOpts = detectImportOptions( ...
    catalogFile, ...
    'VariableNamingRule','preserve');


catalog = readtable( ...
    catalogFile, ...
    catalogOpts);


X0Catalog = catalog{:,2:7};
periodTU = catalog{:,9};
periodDays = catalog{:,10};
muCatalog = catalog{:,12};


summaryOpts = detectImportOptions( ...
    summaryFile, ...
    'VariableNamingRule','preserve');


summary = readtable( ...
    summaryFile, ...
    summaryOpts);


candidateMask = ...
    to_logical_column( ...
        summary.GMOSWouldFindCenter);


candidateRows = ...
    summary.CatalogRow(candidateMask);


candidateRows = ...
    candidateRows(:);


nCandidates = ...
    numel(candidateRows);


fprintf('\n');
fprintf('============================================================\n');
fprintf('LINEAR FLOQUET FORMATION-PREDICTOR SURVEY\n');
fprintf('============================================================\n');

fprintf('Catalog                   : %s\n',catalogFile);
fprintf('Floquet summary           : %s\n',summaryFile);
fprintf('Genuine center candidates : %d\n',nCandidates);
fprintf('Time samples / period     : %d\n',nTimeSamples);
fprintf('Triangle phase samples    : %d\n',nPhaseSamples);


%% ============================================================
%  3. STORAGE
%  ============================================================

success = false(nCandidates,1);
failureMessage = cell(nCandidates,1);

rhoCycles = nan(nCandidates,1);

initialStateVerticalFraction = nan(nCandidates,1);
initialPositionVerticalFraction = nan(nCandidates,1);
initialVelocityVerticalFraction = nan(nCandidates,1);

meanPositionVerticalFraction = nan(nCandidates,1);
maxPositionVerticalFraction = nan(nCandidates,1);

meanStateVerticalFraction = nan(nCandidates,1);
meanVelocityVerticalFraction = nan(nCandidates,1);

medianCircularity = nan(nCandidates,1);
minCircularity = nan(nCandidates,1);

medianEllipseAspect = nan(nCandidates,1);
maxEllipseAspect = nan(nCandidates,1);

positionBreathingRatio = nan(nCandidates,1);

medianPhaseAspect = nan(nCandidates,1);
maxPhaseAspect = nan(nCandidates,1);

normalSynRMS_deg = nan(nCandidates,1);
normalSynMax_deg = nan(nCandidates,1);
normalSynPath_deg = nan(nCandidates,1);

normalInertialRMS_deg = nan(nCandidates,1);
normalInertialMax_deg = nan(nCandidates,1);
normalInertialPath_deg = nan(nCandidates,1);

normalClosure_deg = nan(nCandidates,1);
floquetClosureResidual = nan(nCandidates,1);
baselineIdentityRelError = nan(nCandidates,1);

trackStore = cell(nCandidates,1);


%% ============================================================
%  4. RUN THE LINEAR GEOMETRY SURVEY
%  ============================================================

runParallel = false;

if useParallel

    try

        if license('test','Distrib_Computing_Toolbox')

            pool = gcp('nocreate');

            if isempty(pool)
                parpool;
            end

            runParallel = true;

        end

    catch ME

        warning( ...
            'Parallel setup failed; using serial loop: %s', ...
            ME.message);

    end

end


fprintf('\nTransporting center Floquet modes...\n');

tic;


if runParallel

    parfor kk = 1:nCandidates

        row = candidateRows(kk);

        try

            x0 = X0Catalog(row,:).';
            T = periodTU(row);
            mu = muCatalog(row);

            M_eigs = monodromy_CR3BP([0,T],x0,mu);

            V = M_eigs(:,1:6);
            D = M_eigs(:,7:12);

            cen = gmos_center_eigpair_from_eigs( ...
                V, ...
                D, ...
                centerMode, ...
                centerOpts);

            fg = transport_floquet_center_geometry_CR3BP( ...
                [0,T], ...
                x0, ...
                mu, ...
                cen.w, ...
                nTimeSamples, ...
                odeOpts, ...
                nPhaseSamples);

            rhoCycles(kk) = cen.rho0_cycles;

            initialStateVerticalFraction(kk) = ...
                cen.proj.verticalFraction;

            initialPositionVerticalFraction(kk) = ...
                cen.proj.positionVerticalFraction;

            initialVelocityVerticalFraction(kk) = ...
                cen.proj.velocityVerticalFraction;

            meanPositionVerticalFraction(kk) = ...
                fg.metrics.meanPositionVerticalFraction;

            maxPositionVerticalFraction(kk) = ...
                fg.metrics.maxPositionVerticalFraction;

            meanStateVerticalFraction(kk) = ...
                fg.metrics.meanStateVerticalFraction;

            meanVelocityVerticalFraction(kk) = ...
                fg.metrics.meanVelocityVerticalFraction;

            medianCircularity(kk) = ...
                fg.metrics.medianCircularity;

            minCircularity(kk) = ...
                fg.metrics.minCircularity;

            medianEllipseAspect(kk) = ...
                fg.metrics.medianEllipseAspect;

            maxEllipseAspect(kk) = ...
                fg.metrics.maxEllipseAspect;

            positionBreathingRatio(kk) = ...
                fg.metrics.positionBreathingRatio;

            medianPhaseAspect(kk) = ...
                fg.metrics.medianPhaseAspect;

            maxPhaseAspect(kk) = ...
                fg.metrics.maxPhaseAspect;

            normalSynRMS_deg(kk) = ...
                fg.metrics.synodic.RMSExcursion_deg;

            normalSynMax_deg(kk) = ...
                fg.metrics.synodic.maxExcursion_deg;

            normalSynPath_deg(kk) = ...
                fg.metrics.synodic.pathLength_deg;

            normalInertialRMS_deg(kk) = ...
                fg.metrics.inertial.RMSExcursion_deg;

            normalInertialMax_deg(kk) = ...
                fg.metrics.inertial.maxExcursion_deg;

            normalInertialPath_deg(kk) = ...
                fg.metrics.inertial.pathLength_deg;

            normalClosure_deg(kk) = ...
                fg.normalClosure_deg;

            floquetClosureResidual(kk) = ...
                fg.floquetClosureResidual;

            baselineIdentityRelError(kk) = ...
                fg.metrics.maxBaselineIdentityRelError;

            trackStore{kk} = fg;

            success(kk) = true;

        catch ME

            success(kk) = false;
            failureMessage{kk} = ME.message;

        end

    end


else

    for kk = 1:nCandidates

        row = candidateRows(kk);

        if mod(kk,25)==1 || kk==nCandidates

            fprintf('  candidate %d / %d (catalog row %d)\n', ...
                kk,nCandidates,row);

        end

        try

            x0 = X0Catalog(row,:).';
            T = periodTU(row);
            mu = muCatalog(row);

            M_eigs = monodromy_CR3BP([0,T],x0,mu);

            V = M_eigs(:,1:6);
            D = M_eigs(:,7:12);

            cen = gmos_center_eigpair_from_eigs( ...
                V,D,centerMode,centerOpts);

            fg = transport_floquet_center_geometry_CR3BP( ...
                [0,T],x0,mu,cen.w, ...
                nTimeSamples,odeOpts,nPhaseSamples);

            rhoCycles(kk) = cen.rho0_cycles;

            initialStateVerticalFraction(kk) = cen.proj.verticalFraction;
            initialPositionVerticalFraction(kk) = cen.proj.positionVerticalFraction;
            initialVelocityVerticalFraction(kk) = cen.proj.velocityVerticalFraction;

            meanPositionVerticalFraction(kk) = fg.metrics.meanPositionVerticalFraction;
            maxPositionVerticalFraction(kk) = fg.metrics.maxPositionVerticalFraction;

            meanStateVerticalFraction(kk) = fg.metrics.meanStateVerticalFraction;
            meanVelocityVerticalFraction(kk) = fg.metrics.meanVelocityVerticalFraction;

            medianCircularity(kk) = fg.metrics.medianCircularity;
            minCircularity(kk) = fg.metrics.minCircularity;

            medianEllipseAspect(kk) = fg.metrics.medianEllipseAspect;
            maxEllipseAspect(kk) = fg.metrics.maxEllipseAspect;

            positionBreathingRatio(kk) = fg.metrics.positionBreathingRatio;

            medianPhaseAspect(kk) = fg.metrics.medianPhaseAspect;
            maxPhaseAspect(kk) = fg.metrics.maxPhaseAspect;

            normalSynRMS_deg(kk) = fg.metrics.synodic.RMSExcursion_deg;
            normalSynMax_deg(kk) = fg.metrics.synodic.maxExcursion_deg;
            normalSynPath_deg(kk) = fg.metrics.synodic.pathLength_deg;

            normalInertialRMS_deg(kk) = fg.metrics.inertial.RMSExcursion_deg;
            normalInertialMax_deg(kk) = fg.metrics.inertial.maxExcursion_deg;
            normalInertialPath_deg(kk) = fg.metrics.inertial.pathLength_deg;

            normalClosure_deg(kk) = fg.normalClosure_deg;
            floquetClosureResidual(kk) = fg.floquetClosureResidual;
            baselineIdentityRelError(kk) = fg.metrics.maxBaselineIdentityRelError;

            trackStore{kk} = fg;

            success(kk) = true;

        catch ME

            success(kk) = false;
            failureMessage{kk} = ME.message;

        end

    end

end


runtime_s = toc;


fprintf('\nRuntime = %.3f s\n',runtime_s);
fprintf('Successful transported modes = %d / %d\n', ...
    nnz(success),nCandidates);


%% ============================================================
%  5. OUTPUT TABLE
%  ============================================================

predictorTable = table( ...
    candidateRows, ...
    periodTU(candidateRows), ...
    periodDays(candidateRows), ...
    rhoCycles, ...
    initialStateVerticalFraction, ...
    initialPositionVerticalFraction, ...
    initialVelocityVerticalFraction, ...
    meanStateVerticalFraction, ...
    meanPositionVerticalFraction, ...
    maxPositionVerticalFraction, ...
    meanVelocityVerticalFraction, ...
    medianCircularity, ...
    minCircularity, ...
    medianEllipseAspect, ...
    maxEllipseAspect, ...
    positionBreathingRatio, ...
    medianPhaseAspect, ...
    maxPhaseAspect, ...
    normalSynRMS_deg, ...
    normalSynMax_deg, ...
    normalSynPath_deg, ...
    normalInertialRMS_deg, ...
    normalInertialMax_deg, ...
    normalInertialPath_deg, ...
    normalClosure_deg, ...
    floquetClosureResidual, ...
    baselineIdentityRelError, ...
    success, ...
    'VariableNames',{ ...
        'CatalogRow', ...
        'PeriodTU', ...
        'PeriodDays', ...
        'RhoCycles', ...
        'InitialStateVerticalFraction', ...
        'InitialPositionVerticalFraction', ...
        'InitialVelocityVerticalFraction', ...
        'MeanStateVerticalFraction', ...
        'MeanPositionVerticalFraction', ...
        'MaxPositionVerticalFraction', ...
        'MeanVelocityVerticalFraction', ...
        'MedianEllipseCircularity', ...
        'MinEllipseCircularity', ...
        'MedianEllipseAspect', ...
        'MaxEllipseAspect', ...
        'PositionBreathingRatio', ...
        'MedianLinearTriangleAspect', ...
        'MaxLinearTriangleAspect', ...
        'NormalSynodicRMSExcursion_deg', ...
        'NormalSynodicMaxExcursion_deg', ...
        'NormalSynodicPathLength_deg', ...
        'NormalInertialRMSExcursion_deg', ...
        'NormalInertialMaxExcursion_deg', ...
        'NormalInertialPathLength_deg', ...
        'NormalClosure_deg', ...
        'FloquetClosureResidual', ...
        'BaselineRMSIdentityRelError', ...
        'Success'});


disp(predictorTable);


%% ============================================================
%  6. INTERNAL VALIDATION
%  ============================================================

valid = ...
    success & ...
    isfinite(floquetClosureResidual);


fprintf('\n');
fprintf('============================================================\n');
fprintf('LINEAR-PREDICTOR INTERNAL CHECKS\n');
fprintf('============================================================\n');

fprintf('Max Floquet closure residual        = %.3e\n', ...
    max(floquetClosureResidual(valid)));

fprintf('Max plane-normal closure error      = %.3e deg\n', ...
    max(normalClosure_deg(valid)));

fprintf('Max B_RMS=sqrt(3)R_F relative error = %.3e\n', ...
    max(baselineIdentityRelError(valid)));


%% ============================================================
%  7. DESIGN-MAP FIGURE
%  ============================================================

figDesign = figure( ...
    'Name','Floquet formation-predictor design map', ...
    'Color','w', ...
    'Position',[100 100 1450 800]);


tl = tiledlayout( ...
    figDesign, ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


good = ...
    success & ...
    isfinite(normalSynRMS_deg) & ...
    isfinite(medianCircularity);


%% Intrinsic normal sweep versus ellipse circularity

ax = nexttile(tl);

scatter( ...
    ax, ...
    medianCircularity(good), ...
    normalSynRMS_deg(good), ...
    35, ...
    rhoCycles(good), ...
    'filled');

grid(ax,'on');

xlabel(ax,'Median center-ellipse circularity $\chi=\sigma_2/\sigma_1$');
ylabel(ax,'Synodic normal RMS excursion [deg]');

title(ax,'Intrinsic formation morphology');

cb = colorbar(ax);
ylabel(cb,'$\rho_0/(2\pi)$ [cycles]');


%% Inertial normal sweep versus intrinsic sweep

ax = nexttile(tl);

scatter( ...
    ax, ...
    normalSynRMS_deg(good), ...
    normalInertialRMS_deg(good), ...
    35, ...
    meanPositionVerticalFraction(good), ...
    'filled');

grid(ax,'on');

xlabel(ax,'Synodic normal RMS excursion [deg]');
ylabel(ax,'Inertial normal RMS excursion [deg]');

title(ax,'Intrinsic plane motion versus fixed-sky pointing motion');

cb = colorbar(ax);
ylabel(cb,'Mean $f_{v,\mathrm{pos}}$');


%% Circularity versus phase-sensitive triangle distortion

ax = nexttile(tl);

scatter( ...
    ax, ...
    medianCircularity(good), ...
    maxPhaseAspect(good), ...
    35, ...
    rhoCycles(good), ...
    'filled');

grid(ax,'on');

xlabel(ax,'Median ellipse circularity $\chi$');
ylabel(ax,'Max linear triangle aspect ratio');

title(ax,'Predictor of common-phase sensitivity');

cb = colorbar(ax);
ylabel(cb,'$\rho_0/(2\pi)$ [cycles]');


%% Breathing versus normal sweep

ax = nexttile(tl);

scatter( ...
    ax, ...
    positionBreathingRatio(good), ...
    normalSynRMS_deg(good), ...
    35, ...
    meanPositionVerticalFraction(good), ...
    'filled');

grid(ax,'on');

xlabel(ax,'Position-scale breathing $R_{F,\max}/R_{F,\min}$');
ylabel(ax,'Synodic normal RMS excursion [deg]');

title(ax,'Baseline breathing versus pointing morphology');

cb = colorbar(ax);
ylabel(cb,'Mean $f_{v,\mathrm{pos}}$');


title( ...
    tl, ...
    ['Scale-free Floquet predictors of small-QPO ', ...
     'three-collector formation behavior']);


%% ============================================================
%  8. INVENTORY FIGURE
%  ============================================================

figInventory = figure( ...
    'Name','Floquet formation predictors in catalog order', ...
    'Color','w', ...
    'Position',[110 110 1500 850]);


tl = tiledlayout( ...
    figInventory, ...
    4,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');


inventoryData = { ...
    normalSynRMS_deg, ...
    medianCircularity, ...
    positionBreathingRatio, ...
    maxPhaseAspect};


inventoryY = { ...
    'normal RMS [deg]', ...
    'circularity $\chi$', ...
    '$R_{F,\max}/R_{F,\min}$', ...
    'max triangle aspect'};


inventoryTitle = { ...
    'Synodic Floquet-plane normal excursion', ...
    'Median center-ellipse circularity', ...
    'Position-scale breathing', ...
    'Predicted common-phase triangle distortion'};


for k = 1:4

    ax = nexttile(tl);

    scatter( ...
        ax, ...
        candidateRows(success), ...
        inventoryData{k}(success), ...
        15, ...
        rhoCycles(success), ...
        'filled');

    grid(ax,'on');

    xlabel(ax,'JPL catalog row');
    ylabel(ax,inventoryY{k});

    title(ax,inventoryTitle{k});

    add_highlight_rows(ax,highlightRows);

end


title( ...
    tl, ...
    ['Floquet-geometry inventory in JPL catalog order ', ...
     '(not a continuation diagram)']);


%% ============================================================
%  9. REPRESENTATIVE NORMAL TRACKS
%  ============================================================

availableHighlightRows = ...
    highlightRows(ismember(highlightRows,candidateRows));


if ~isempty(availableHighlightRows)

    figNormals = figure( ...
        'Name','Representative linear Floquet normal tracks', ...
        'Color','w', ...
        'Position',[100 100 1500 750]);


    nPlot = numel(availableHighlightRows);

    nCols = min(3,nPlot);
    nRows = ceil(nPlot/nCols);

    tl = tiledlayout( ...
        figNormals, ...
        nRows,nCols, ...
        'TileSpacing','compact', ...
        'Padding','compact');


    [xs,ys,zs] = sphere(30);


    for j = 1:nPlot

        row = availableHighlightRows(j);

        kk = find(candidateRows==row,1,'first');

        if isempty(kk) || ~success(kk)
            continue
        end

        fg = trackStore{kk};

        ax = nexttile(tl);

        surf( ...
            ax, ...
            xs,ys,zs, ...
            'FaceColor',[0.8 0.8 0.8], ...
            'FaceAlpha',0.05, ...
            'EdgeColor',[0.75 0.75 0.75], ...
            'EdgeAlpha',0.18);

        hold(ax,'on');
        grid(ax,'on');
        axis(ax,'equal');

        plot3( ...
            ax, ...
            fg.nSynodic(:,1), ...
            fg.nSynodic(:,2), ...
            fg.nSynodic(:,3), ...
            'LineWidth',1.8);

        xlabel(ax,'$n_x$');
        ylabel(ax,'$n_y$');
        zlabel(ax,'$n_z$');

        view(ax,35,25);

        title(ax,sprintf( ...
            ['row %d: $\\rho_0/(2\\pi)=%.3f$\n', ...
             '$\\Delta n_{\\rm RMS}=%.2f^\\circ$, $\\chi_{\\rm med}=%.2f$'], ...
            row, ...
            rhoCycles(kk), ...
            normalSynRMS_deg(kk), ...
            medianCircularity(kk)));

    end


    title( ...
        tl, ...
        'Predicted small-QPO plane-normal tracks from transported Floquet modes');

end


%% ============================================================
%  10. REPRESENTATIVE TIME HISTORIES
%  ============================================================

if ~isempty(availableHighlightRows)

    figHist = figure( ...
        'Name','Representative Floquet predictor histories', ...
        'Color','w', ...
        'Position',[100 100 1500 900]);


    tl = tiledlayout( ...
        figHist, ...
        4,1, ...
        'TileSpacing','compact', ...
        'Padding','compact');


    colors = lines(numel(availableHighlightRows));


    for panel = 1:4

        ax = nexttile(tl);
        hold(ax,'on');
        grid(ax,'on');

        for j = 1:numel(availableHighlightRows)

            row = availableHighlightRows(j);

            kk = find(candidateRows==row,1,'first');

            if isempty(kk) || ~success(kk)
                continue
            end

            fg = trackStore{kk};

            switch panel

                case 1

                    y = fg.positionVerticalFraction;
                    yLabel = '$f_{v,\mathrm{pos}}$';
                    ttl = 'Transported position-space vertical fraction';

                case 2

                    y = fg.circularity;
                    yLabel = '$\chi=\sigma_2/\sigma_1$';
                    ttl = 'Instantaneous center-ellipse circularity';

                case 3

                    y = fg.positionRMSRadius / ...
                        median(fg.positionRMSRadius,'omitnan');

                    yLabel = '$R_F/\mathrm{median}(R_F)$';
                    ttl = 'Scale-free baseline breathing';

                case 4

                    nMean = fg.metrics.synodic.meanAxis;

                    c = abs(fg.nSynodic*nMean.');

                    c = min(1,max(-1,c));

                    y = acosd(c);

                    yLabel = 'normal excursion [deg]';
                    ttl = 'Plane-normal excursion from mean axis';

            end

            plot( ...
                ax, ...
                fg.tau, ...
                y, ...
                'Color',colors(j,:), ...
                'DisplayName',sprintf('row %d',row));

        end

        xlabel(ax,'$t/T$');
        ylabel(ax,yLabel);
        title(ax,ttl);

        if panel == 1
            legend(ax,'Location','best');
        end

    end


    title( ...
        tl, ...
        'Linear Floquet predictors over one parent-orbit period');

end


%% ============================================================
%  11. SAVE
%  ============================================================

if saveResults

    csvFile = fullfile( ...
        outputDir, ...
        'JPL_Halo_Floquet_Geometry_Predictors.csv');


    matFile = fullfile( ...
        outputDir, ...
        'JPL_Halo_Floquet_Geometry_Predictors.mat');


    writetable( ...
        predictorTable, ...
        csvFile);


    save( ...
        matFile, ...
        'predictorTable', ...
        'candidateRows', ...
        'trackStore', ...
        'runtime_s', ...
        'nTimeSamples', ...
        'nPhaseSamples', ...
        '-v7.3');


    fprintf('\nSaved:\n');
    fprintf('  %s\n',csvFile);
    fprintf('  %s\n',matFile);

end


%% ============================================================
%  12. INTERPRETATION
%  ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('FORMATION-PREDICTOR INTERPRETATION\n');
fprintf('============================================================\n');

fprintf([ ...
    'NormalSynodicRMSExcursion_deg measures intrinsic rotation of the\\n', ...
    'linearized center plane over one parent period.\\n\\n']);

fprintf([ ...
    'MedianEllipseCircularity chi=sigma2/sigma1 measures the shape of the\\n', ...
    'configuration-space center ellipse. chi=1 is circular; chi->0 is\\n', ...
    'line-like. Lower chi should imply stronger collector-phase sensitivity.\\n\\n']);

fprintf([ ...
    'PositionBreathingRatio measures scale variation of the linearized\\n', ...
    'formation around the parent orbit. Absolute scale is arbitrary because\\n', ...
    'a Floquet eigenvector can be multiplied by any complex scalar.\\n\\n']);

fprintf([ ...
    'RhoCycles is the center-phase advance per parent-orbit period.\\n\\n']);

fprintf([ ...
    'The next validation step is to compare n_F(t) directly against the\\n', ...
    'normal history of small corrected GMOS QPO formations for selected\\n', ...
    'parents such as rows 82, 125, and 197.\\n']);

fprintf('============================================================\n');


%% ========================================================================
%  LOCAL FUNCTIONS
%  ========================================================================


function x = to_logical_column(x)
%TO_LOGICAL_COLUMN

    if islogical(x)
        return
    end

    if isnumeric(x)

        x = x ~= 0;
        return

    end

    if iscell(x)

        x = string(x);

    end

    if isstring(x) || ischar(x)

        x = strcmpi(string(x),"true") | ...
            strcmpi(string(x),"1");

        return

    end

    error('Unsupported logical-column type.');

end


function add_highlight_rows(ax,rows)
%ADD_HIGHLIGHT_ROWS

    hold(ax,'on');

    for r = rows(:).'

        xline( ...
            ax, ...
            r, ...
            ':', ...
            sprintf('%d',r), ...
            'LabelVerticalAlignment','bottom', ...
            'HandleVisibility','off');

    end

end
